// Generated by scripts/generate_turn_contract.py; do not edit.
// Source: loopx/control_plane/turn_loop_controller_contract_v0.json
// SHA256: 184046656dada524b5412be128424b840dc1d490eef5bf8a0c9e9e5bb786492a

export const TURN_RESULT_KINDS = [
  "validated_progress",
  "validated_completion",
  "repair_required",
  "replan_required",
  "user_action_required",
  "wait",
  "iteration_failed",
  "host_failure",
  "validation_failed",
  "writeback_failed",
  "quota_spend_failed",
  "terminal_closeout_failed",
] as const;
export type LoopXTurnResultKindValue = (typeof TURN_RESULT_KINDS)[number];

export const TURN_ROUTES = [
  "ready_for_host",
  "capability_action_required",
  "repair_required",
  "replan_required",
  "user_action_required",
  "wait",
  "blocked",
  "contract_error",
] as const;
export type LoopXTurnRouteValue = (typeof TURN_ROUTES)[number];

export const LOOP_DISPOSITIONS = [
  "run_now",
  "capability_action_required",
  "wait",
  "stop",
  "user_action_required",
  "repair",
  "replan",
  "terminal",
] as const;
export type LoopDispositionValue = (typeof LOOP_DISPOSITIONS)[number];

export type TurnResultKind = LoopXTurnResultKindValue;
export const TURN_CONTROLLER_CONTRACT = {
  "schema_version": "loop_turn_controller_decision_contract_v0",
  "evaluation": "ordered_checks_then_first_matching_return",
  "qualification": {
    "receipt": "ValidatedTurnReceipt.from_execution; material settlement, durable completion and host failure qualification remain admission preconditions",
    "budget": "BoundedTurnBudget; strict integers, finite ranges and nonempty lineage remain admission preconditions",
    "rejection": "Checks raise ValueError; rejection is not a LoopDisposition. A check is evaluated only if reached and its finite when partition matches.",
    "result_route_relation": "No unary result-kind to route projection exists. driver._typed_route qualifies quota input; decide_loop_disposition combines receipt, quota, causal predecessor and budget. Named admission primitives remain Python-owned."
  },
  "partitions": {
    "receipt_kind": {
      "owner": "LoopXTurnResultKind",
      "additional": [
        "absent"
      ]
    },
    "route": {
      "owner": "LoopXTurnRoute"
    },
    "receipt_present": [
      false,
      true
    ],
    "terminal_action": [
      false,
      true
    ],
    "completion": [
      "no_followup",
      "successor",
      "active_goal",
      "not_applicable"
    ],
    "host_failure_present": [
      false,
      true
    ],
    "retry_state": [
      "available",
      "exhausted",
      "not_retryable",
      "not_applicable"
    ],
    "budget_state": [
      "absent",
      "available",
      "exhausted",
      "not_applicable"
    ]
  },
  "checks": {
    "envelope": "Shared _typed_route rejects schema/signature/capability-intent contract_error before user projection; user action then overrides a valid route.",
    "decision_actor": "Require fresh nonempty goal and agent lineage.",
    "receipt_binding": "Require predecessor_turn_key, then equality to receipt.turn_key, then matching goal and agent, in that order.",
    "initial_terminal": "Require terminal_no_followup state for the terminal action.",
    "initial_todo": "Require selected Todo unless the route projects wait or user_action_required.",
    "completion_terminal": "Require both terminal_no_followup action and state.",
    "completion_todo": "Require selected Todo; successor must be declared; active_goal must not reselect completed Todo.",
    "receipt_todo": "Present selected Todo must equal receipt Todo. Absent Todo rejects progress unless route is user_action_required or wait; other admitted cases inherit receipt Todo.",
    "progress_budget": "Require bounded budget, then matching effective goal/agent/todo lineage; exhaustion is evaluated only after these checks.",
    "host_retry": "Normalize host failure with existing retry policy; available iff retryable and attempt < max_attempts; otherwise exhausted or not_retryable."
  },
  "route_projection": {
    "ready_for_host": "run_now",
    "capability_action_required": "capability_action_required",
    "replan_required": "replan",
    "repair_required": "repair",
    "user_action_required": "user_action_required",
    "wait": "wait",
    "blocked": "wait",
    "contract_error": null
  },
  "rules": [
    {
      "id": "check_envelope",
      "when": {},
      "check": "envelope"
    },
    {
      "id": "check_decision_actor",
      "when": {},
      "check": "decision_actor"
    },
    {
      "id": "check_receipt_binding",
      "when": {
        "receipt_present": [
          true
        ]
      },
      "check": "receipt_binding"
    },
    {
      "id": "capability",
      "when": {
        "route": [
          "capability_action_required"
        ],
        "receipt_kind": [
          "absent",
          "validated_progress",
          "validated_completion"
        ]
      },
      "disposition": "capability_action_required",
      "reason": "fresh capability intent requires its adapter before a host turn",
      "lineage": "decision",
      "extra": "capability"
    },
    {
      "id": "check_initial_terminal",
      "when": {
        "receipt_kind": [
          "absent"
        ],
        "terminal_action": [
          true
        ]
      },
      "check": "initial_terminal"
    },
    {
      "id": "initial_terminal",
      "when": {
        "receipt_kind": [
          "absent"
        ],
        "terminal_action": [
          true
        ]
      },
      "disposition": "terminal",
      "reason": "fresh Goal frontier proves terminal no-follow-up",
      "lineage": "decision"
    },
    {
      "id": "check_initial_todo",
      "when": {
        "receipt_kind": [
          "absent"
        ]
      },
      "check": "initial_todo"
    },
    {
      "id": "initial_route",
      "when": {
        "receipt_kind": [
          "absent"
        ]
      },
      "disposition": "project_route",
      "reason": {
        "run_now": "no prior receipt and fresh decision allows delivery",
        "wait": "fresh decision is a quiet no-spend wait",
        "repair": "fresh decision requires repair",
        "user_action_required": "fresh decision projects a concrete user action",
        "replan": "fresh decision requires replan"
      },
      "lineage": "decision"
    },
    {
      "id": "check_completion_terminal",
      "when": {
        "receipt_kind": [
          "validated_completion"
        ],
        "completion": [
          "no_followup"
        ]
      },
      "check": "completion_terminal"
    },
    {
      "id": "completion_terminal",
      "when": {
        "receipt_kind": [
          "validated_completion"
        ],
        "completion": [
          "no_followup"
        ]
      },
      "disposition": "terminal",
      "reason": "durable no-follow-up and fresh Goal frontier prove terminal closure",
      "lineage": "receipt"
    },
    {
      "id": "check_completion_todo",
      "when": {
        "receipt_kind": [
          "validated_completion"
        ]
      },
      "check": "completion_todo"
    },
    {
      "id": "completion_successor",
      "when": {
        "receipt_kind": [
          "validated_completion"
        ],
        "completion": [
          "successor"
        ]
      },
      "disposition": "project_route",
      "reason": {
        "default": "durable Todo completion continues through its declared successor",
        "user_action_required": "fresh decision projects a concrete user action after Todo completion",
        "replan": "fresh decision requires replan after Todo completion"
      },
      "lineage": "decision"
    },
    {
      "id": "completion_active_goal",
      "when": {
        "receipt_kind": [
          "validated_completion"
        ],
        "completion": [
          "active_goal"
        ]
      },
      "disposition": "project_route",
      "reason": {
        "default": "durable Todo completion continues through the fresh Goal frontier",
        "user_action_required": "fresh decision projects a concrete user action after Todo completion",
        "replan": "fresh decision requires replan after Todo completion"
      },
      "lineage": "decision"
    },
    {
      "id": "check_receipt_todo",
      "when": {},
      "check": "receipt_todo"
    },
    {
      "id": "decision_user",
      "when": {
        "route": [
          "user_action_required"
        ]
      },
      "disposition": "user_action_required",
      "reason": "fresh decision projects a concrete user action",
      "lineage": "effective"
    },
    {
      "id": "check_progress_budget",
      "when": {
        "receipt_kind": [
          "validated_progress"
        ]
      },
      "check": "progress_budget"
    },
    {
      "id": "progress_exhausted",
      "when": {
        "receipt_kind": [
          "validated_progress"
        ],
        "budget_state": [
          "exhausted"
        ]
      },
      "disposition": "replan",
      "reason": "bounded turn budget exhausted; replan before another Turn",
      "lineage": "effective"
    },
    {
      "id": "progress_route",
      "when": {
        "receipt_kind": [
          "validated_progress"
        ]
      },
      "disposition": "project_route",
      "reason": {
        "run_now": "validated progress with fresh decision allowing the next turn",
        "wait": "validated progress but fresh decision does not allow the next turn yet",
        "repair": "fresh decision requires repair after progress",
        "user_action_required": "fresh decision projects a concrete user action",
        "replan": "fresh decision requires replan after progress"
      },
      "lineage": "effective"
    },
    {
      "id": "receipt_replan_required",
      "when": {
        "receipt_kind": [
          "replan_required"
        ]
      },
      "disposition": "replan",
      "reason": "turn receipt requires replan",
      "lineage": "effective"
    },
    {
      "id": "receipt_repair_required",
      "when": {
        "receipt_kind": [
          "repair_required"
        ]
      },
      "disposition": "repair",
      "reason": "turn receipt requires repair",
      "lineage": "effective"
    },
    {
      "id": "receipt_user_action_required",
      "when": {
        "receipt_kind": [
          "user_action_required"
        ]
      },
      "disposition": "user_action_required",
      "reason": "turn receipt projects a concrete user action",
      "lineage": "effective"
    },
    {
      "id": "receipt_wait",
      "when": {
        "receipt_kind": [
          "wait"
        ]
      },
      "disposition": "wait",
      "reason": "turn receipt is a typed no-spend wait",
      "lineage": "effective"
    },
    {
      "id": "receipt_iteration_failed",
      "when": {
        "receipt_kind": [
          "iteration_failed"
        ]
      },
      "disposition": "stop",
      "reason": "the iteration reported failure and no typed continuation was requested; stop this iteration without retry or successor",
      "lineage": "effective",
      "extra": "iteration_stop"
    },
    {
      "id": "host_replan",
      "when": {
        "receipt_kind": [
          "host_failure"
        ],
        "host_failure_present": [
          true
        ],
        "route": [
          "replan_required"
        ]
      },
      "disposition": "replan",
      "reason": "fresh decision requires replan after host failure",
      "lineage": "effective"
    },
    {
      "id": "host_repair",
      "when": {
        "receipt_kind": [
          "host_failure"
        ],
        "host_failure_present": [
          true
        ],
        "route": [
          "repair_required"
        ]
      },
      "disposition": "repair",
      "reason": "fresh decision requires repair after host failure",
      "lineage": "effective"
    },
    {
      "id": "check_host_retry",
      "when": {
        "receipt_kind": [
          "host_failure"
        ],
        "host_failure_present": [
          true
        ]
      },
      "check": "host_retry"
    },
    {
      "id": "host_retry",
      "when": {
        "receipt_kind": [
          "host_failure"
        ],
        "host_failure_present": [
          true
        ],
        "retry_state": [
          "available"
        ]
      },
      "disposition": "wait",
      "reason": "retryable host failure {failure_kind} requires bounded backoff before the same Turn is resumed",
      "lineage": "effective",
      "extra": "retry"
    },
    {
      "id": "host_exhausted",
      "when": {
        "receipt_kind": [
          "host_failure"
        ],
        "host_failure_present": [
          true
        ],
        "retry_state": [
          "exhausted"
        ]
      },
      "disposition": "repair",
      "reason": "retryable host failure {failure_kind} exhausted its bounded attempt budget",
      "lineage": "effective"
    },
    {
      "id": "failed_receipt",
      "when": {
        "receipt_kind": [
          "host_failure",
          "validation_failed",
          "writeback_failed",
          "quota_spend_failed",
          "terminal_closeout_failed"
        ]
      },
      "disposition": "repair",
      "reason": "turn receipt ended in {receipt_kind}; route to repair before any successor turn",
      "lineage": "effective"
    }
  ],
  "vocabularies": {
    "turn_result_kind": {
      "VALIDATED_PROGRESS": "validated_progress",
      "VALIDATED_COMPLETION": "validated_completion",
      "REPAIR_REQUIRED": "repair_required",
      "REPLAN_REQUIRED": "replan_required",
      "USER_ACTION_REQUIRED": "user_action_required",
      "WAIT": "wait",
      "ITERATION_FAILED": "iteration_failed",
      "HOST_FAILURE": "host_failure",
      "VALIDATION_FAILED": "validation_failed",
      "WRITEBACK_FAILED": "writeback_failed",
      "QUOTA_SPEND_FAILED": "quota_spend_failed",
      "TERMINAL_CLOSEOUT_FAILED": "terminal_closeout_failed"
    },
    "turn_route": {
      "READY_FOR_HOST": "ready_for_host",
      "CAPABILITY_ACTION_REQUIRED": "capability_action_required",
      "REPAIR_REQUIRED": "repair_required",
      "REPLAN_REQUIRED": "replan_required",
      "USER_ACTION_REQUIRED": "user_action_required",
      "WAIT": "wait",
      "BLOCKED": "blocked",
      "CONTRACT_ERROR": "contract_error"
    },
    "loop_disposition": {
      "RUN_NOW": "run_now",
      "CAPABILITY_ACTION_REQUIRED": "capability_action_required",
      "WAIT": "wait",
      "STOP": "stop",
      "USER_ACTION_REQUIRED": "user_action_required",
      "REPAIR": "repair",
      "REPLAN": "replan",
      "TERMINAL": "terminal"
    }
  }
} as const;
export const ROUTE_TO_DISPOSITION = TURN_CONTROLLER_CONTRACT.route_projection;
