from __future__ import annotations

from copy import deepcopy
import json
from pathlib import Path
from typing import Any

import pytest

from loopx.control_plane.effect_program import interpret_quota_should_run_packet
from loopx.control_plane.quota.turn_envelope import (
    TURN_ENVELOPE_BUDGET_BYTES,
    build_turn_envelope,
    quota_action_signature_document,
    turn_envelope_action_signature_document,
)
from loopx.control_plane.quota.task_orchestration import (
    apply_task_orchestration_contract,
)
from loopx.control_plane.scheduler.execution_context import (
    SchedulerRuntimeProfile,
    scheduler_execution_context_for_runtime_profile,
)
from loopx.control_plane.work_items.interaction_contract import (
    protocol_action_packet_fields,
    render_protocol_action_packet_summary,
)
from loopx.control_plane.turn_driver.host_candidate import extract_turn_authority


STATE_MATRIX = json.loads(
    (Path(__file__).parent / "fixtures" / "turn_envelope_state_matrix.json").read_text(
        encoding="utf-8"
    )
)

# Synthetic bounded-delivery example of the v0 wire format in PR #1898,
# fa1a7099400841568d082abc1f60b410311c8945:
# work_items/interaction_contract.py::protocol_action_packet_fields and
# tests/test_turn_envelope.py::test_protocol_packet_derivation_*.
# Literal input, never regenerated by the writer being tested. This is format
# evidence, not a production archive or approval of a retirement window.
HISTORICAL_V0_SUMMARY = (
    "actor=agent user_action_required=false agent_action_required=true "
    "quiet_noop_allowed=false lane=advancement_task automation=execute_bounded_work "
    "scheduler=run_now pause_allowed=false llm=no_api "
    "agent_action=advance one product-path slice"
)


def _legacy_protocol_packet(source: dict[str, Any]) -> dict[str, Any]:
    """Build legacy-only fixture input; live quota writers no longer emit it.

    The independently authored HISTORICAL_V0_SUMMARY exercises compatibility
    separately, so this adapter is not the historical correctness oracle.
    """
    return {
        "schema_version": "protocol_action_packet_v0",
        "summary": render_protocol_action_packet_summary(protocol_action_packet_fields(source)),
    }


def _compat_decision(packet_format: str) -> dict[str, Any]:
    source = _full_decision()
    source.pop("protocol_action_packet")
    if packet_format != "absent":
        source["protocol_action_packet"] = {
            "schema_version": "protocol_action_packet_v0",
            "summary": (
                "legacy opaque packet"
                if packet_format == "opaque"
                else HISTORICAL_V0_SUMMARY
            ),
        }
    if packet_format == "residue":
        source["interaction_contract"]["agent_channel"]["primary_action"] = (
            "a newer canonical action projection"
        )
    return source


def _deep_update(target: dict[str, Any], patch: dict[str, Any]) -> None:
    for key, value in patch.items():
        if isinstance(value, dict) and isinstance(target.get(key), dict):
            _deep_update(target[key], value)
        else:
            target[key] = deepcopy(value)


def _path_value(payload: dict[str, Any], path: str) -> Any:
    current: Any = payload
    for part in path.split("."):
        assert isinstance(current, dict), (path, part, current)
        current = current[part]
    return current


def _full_decision() -> dict[str, object]:
    source: dict[str, object] = {
        "ok": True,
        "goal_id": "fixture-goal",
        "decision": "run",
        "should_run": True,
        "effective_action": "normal_run",
        "state": "eligible",
        "normal_delivery_allowed": True,
        "recovery_delivery_allowed": False,
        "self_repair_allowed": False,
        "capability_repair_allowed": False,
        "workspace_repair_allowed": False,
        "safe_bypass_allowed": False,
        "reason": "eligible fixture",
        "action_required": False,
        "open_count": 0,
        "recommended_action": "implement one bounded public-safe slice",
        "agent_identity": {"agent_id": "codex-fixture"},
        "selected_todo": {
            "todo_id": "todo_fixture0001",
            "priority": "P0",
            "status": "open",
            "task_class": "advancement_task",
            "action_kind": "fixture_action",
            "continuation_policy": "same_agent_non_delivery",
            "claimed_by": "codex-fixture",
            "text": "Implement one bounded public-safe slice",
        },
        "interaction_contract": {
            "schema_version": "loopx_interaction_contract_v0",
            "mode": "bounded_delivery",
            "user_channel": {"action_required": False, "notify": "DONT_NOTIFY"},
            "agent_channel": {
                "must_attempt": True,
                "delivery_allowed": True,
                "quiet_noop_allowed": False,
                "primary_action": "advance one product-path slice",
            },
            "cli_channel": {
                "next_cli_actions": [
                    "loopx refresh-state --goal-id fixture-goal --classification validated",
                    "loopx quota spend-slot --goal-id fixture-goal --execute",
                ],
                "spend_allowed_now": False,
                "spend_after_validation": True,
                "spend_policy": "spend once after validated writeback",
            },
            "required_reads": [
                {
                    "kind": "repository",
                    "command": "git status --short",
                    "reason": "inspect state",
                }
            ],
        },
        "goal_boundary": {
            "adapter": {"kind": "fixture", "status": "connected-read-only"},
            "write_scope": ["loopx/**", "tests/**"],
            "requires_parent_approval": ["publish"],
            "guards": ["stop on private material"],
            "stop_condition": "stop before unauthorized production action",
            "rule": "stay_in_scope_or_stop",
        },
        "scheduler_hint": {
            "action": "run_now",
            "cadence_class": "active_work",
            "spend_policy": "spend after validated writeback",
            "codex_app": {
                "apply": "update_automation_cadence_if_possible",
                "host_action": "update_current_heartbeat_rrule",
                "recommended_rrule": "FREQ=MINUTELY;INTERVAL=3",
                "no_spend_for_cadence_change": True,
                "stateful_backoff": {
                    "state_key": "scheduler_hint.codex_app.stateful_backoff",
                    "current_rrule": "FREQ=MINUTELY;INTERVAL=60",
                    "apply_needed": True,
                    "state_status": "reset_required",
                },
                "ack_hint": {
                    "cli_args": [
                        "quota",
                        "scheduler-ack-current",
                        "--goal-id",
                        "fixture-goal",
                        "--execute",
                    ]
                },
            },
        },
        "work_lane_contract": {
            "schema_version": "work_lane_contract_v1",
            "lane": "advancement_task",
            "next_lane": "advancement_task",
            "obligation": "advance_primary_outcome_or_write_blocker",
            "must_attempt_work": True,
            "monitor_policy": "material_transition_only",
            "action": "advance one product-path slice",
            "outcome_followthrough": {
                "required": True,
                "obligation": "advance_primary_outcome_or_write_blocker",
                "accepted_resolution_kinds": [
                    "product_path_execution",
                    "blocker_writeback",
                ],
                "spend_policy": "spend after validated evidence",
            },
        },
        "execution_obligation": {
            "schema_version": "execution_obligation_v0",
            "kind": "work_lane_contract",
            "contract": "work_lane_contract",
            "contract_obligation": "advance_primary_outcome_or_write_blocker",
            "must_attempt_work": True,
            "notify_is_execution_gate": False,
            "reason": "runnable fixture todo",
        },
        "goal_route_hint": {
            "schema_version": "goal_route_hint_v0",
            "kind": "agent_lane_synthesis",
            "route_decision": "run_current_agent_lane",
            "reason": "selected current-agent claimed todo",
            "preserves_goal_next_action": True,
            "goal_next_action_mutation": "none",
        },
        "automation_liveness": {
            "schema_version": "automation_liveness_v0",
            "keep_active": True,
            "pause_allowed": False,
            "automation_action": "execute_bounded_work",
            "reason": "runnable work remains",
            "spend_policy": "spend after validated writeback",
        },
        "handoff_readiness": {
            "ready": True,
            "codex_ready": True,
            "handoff_status": "post_handoff_run_seen",
            "post_handoff_run_seen": True,
            "post_handoff_recent_runs": ["diagnostic-only"],
        },
        "agent_todo_summary": {"large_diagnostic_lane": ["x" * 4_000]},
        "goal_frontier_projection": {"large_diagnostic_lane": ["y" * 4_000]},
        "plan_summary": {"large_diagnostic_lane": ["z" * 4_000]},
    }
    source["protocol_action_packet"] = _legacy_protocol_packet(source)
    return source


@pytest.mark.parametrize(
    "case",
    STATE_MATRIX["cases"],
    ids=[case["name"] for case in STATE_MATRIX["cases"]],
)
def test_turn_envelope_state_matrix_preserves_parity_and_budget(
    case: dict[str, Any],
) -> None:
    source = _full_decision()
    _deep_update(source, case["patch"])
    source["protocol_action_packet"] = _legacy_protocol_packet(source)

    envelope = build_turn_envelope(source)

    assert quota_action_signature_document(
        source
    ) == turn_envelope_action_signature_document(envelope)
    assert envelope["action_signature"]["matches"] is True
    assert envelope["action_signature"]["coverage"] == case.get(
        "expected_action_signature_coverage",
        "turn_envelope_action_dimensions_v0",
    )
    assert (
        envelope["contract_capsule"]["protocol_action_packet"][
            "reconstruction_verified"
        ]
        is True
    )
    assert envelope["compaction"]["within_budget"] is True
    assert envelope["compaction"]["envelope_json_bytes"] <= TURN_ENVELOPE_BUDGET_BYTES
    assert (
        envelope["compaction"]["byte_reduction_ratio"]
        >= case["minimum_reduction_ratio"]
    )
    for path, expected in case["expected"].items():
        assert _path_value(envelope, path) == expected, (case["name"], path)


def test_turn_envelope_matrix_keeps_default_view_opt_in() -> None:
    decision = STATE_MATRIX["promotion_decision"]

    assert decision["state"] == "keep_opt_in"
    assert decision["required_next_evidence"] == [
        "shadow parity from at least one real host integration",
        "no consumer regression when the full decision remains available as a cold path",
        "explicit compatibility acceptance for changing the default CLI view",
    ]


def test_turn_envelope_preserves_action_boundary_and_writeback() -> None:
    source = _full_decision()
    envelope = build_turn_envelope(source)

    assert envelope["schema_version"] == "loopx_turn_envelope_v0"
    assert envelope["view"] == "turn_envelope"
    assert envelope["goal_id"] == "fixture-goal"
    assert envelope["agent_id"] == "codex-fixture"
    assert envelope["action_signature"]["matches"] is True
    assert envelope["action"]["selected_todo"]["todo_id"] == "todo_fixture0001"
    assert envelope["action"]["selected_todo"]["continuation_policy"] == (
        "same_agent_non_delivery"
    )


def test_turn_envelope_compacts_replan_help_without_losing_successor_execution() -> None:
    source = _full_decision()
    successor_command = (
        "loopx todo add --goal-id fixture-goal --role agent "
        "--task-class advancement_task --action-kind validate "
        "--target-key experiment:fixture-next-slice "
        "--text '[P0] next slice' "
        "--claimed-by codex-fixture "
        "--replan-obligation-id replan-0123456789abcdef"
    )
    source["interaction_contract"]["mode"] = "autonomous_replan"
    source["interaction_contract"]["agent_channel"]["primary_action"] = (
        "select one bounded next slice; prefer "
        "replan_action_packet.writeback_contract.successor_command"
    )
    refresh_command = (
        "loopx refresh-state --goal-id fixture-goal "
        "--progress-scope agent_lane --progress-result-class <typed-class>"
    )
    source["interaction_contract"]["cli_channel"]["next_cli_actions"] = [
        "execute replan_action_packet.writeback_contract.successor_command",
        refresh_command,
        "on host_action=end_current_heartbeat: stop",
    ]
    source["replan_action_packet"] = {
        "schema_version": "replan_action_packet_v0",
        "decision": "replan_required",
        "obligation_id": "replan-0123456789abcdef",
        "uncovered_frontier": {
            "baseline": None,
            "required_any_of": ["new_surface", "new_runnable_successor"],
        },
        "required_outcome": "semantic_delta",
        "writeback_contract": {
            "successor_command": successor_command,
            "successor_host_action": "end_current_heartbeat",
        },
        "allowed_terminal": ["exploration_exhausted", "blocked", "no_followup"],
    }

    envelope = build_turn_envelope(source)
    packet = envelope["replan_action_packet"]

    assert "writeback_contract" not in packet
    assert envelope["writeback"]["next_cli_actions"] == [
        successor_command,
        refresh_command,
    ]
    assert envelope["compaction"]["within_budget"] is True
    assert quota_action_signature_document(
        source
    ) == turn_envelope_action_signature_document(envelope)


def test_turn_envelope_derives_canonical_slots_through_effect_turn() -> None:
    source = _full_decision()
    turn = interpret_quota_should_run_packet(
        source,
        goal_id="fixture-goal",
        agent_id="codex-fixture",
    )
    envelope = build_turn_envelope(source)

    assert envelope["action"]["recommended_action"] == (
        turn.observation.recommended_action
    )
    assert envelope["writeback"]["next_cli_actions"] == list(
        turn.next_effect.cli_actions
    )
    assert envelope["scheduler"]["action"] == turn.next_effect.scheduler_action
    assert envelope["scheduler"]["cadence_class"] == turn.next_effect.cadence_class
    assert envelope["action"]["must_attempt"] is True
    assert envelope["user"] == {
        "action_required": False,
        "open_count": 0,
        "notify": "DONT_NOTIFY",
    }
    assert envelope["required_reads"][0]["command"] == "git status --short"
    assert envelope["boundary"]["write_scope"] == ["loopx/**", "tests/**"]
    assert envelope["execution_policy"]["normal_delivery_allowed"] is True
    assert envelope["execution_policy"]["safe_bypass_allowed"] is False
    assert envelope["writeback"]["spend_after_validation"] is True
    assert (
        envelope["scheduler"]["codex_app"]["stateful_backoff"]["apply_needed"] is True
    )
    assert envelope["scheduler"]["codex_app"]["ack_cli_args"][0] == "quota"
    assert (
        envelope["contract_capsule"]["work_lane_contract"]["lane"] == "advancement_task"
    )
    assert (
        envelope["contract_capsule"]["execution_obligation"]["contract_obligation"]
        == "advance_primary_outcome_or_write_blocker"
    )
    assert envelope["contract_capsule"]["automation_liveness"]["pause_allowed"] is False
    assert envelope["contract_capsule"]["protocol_action_packet"] == {
        "schema_version": "protocol_action_packet_v0",
        "present": True,
        "summary_hash": envelope["contract_capsule"]["protocol_action_packet"][
            "summary_hash"
        ],
        "derivation_status": "verified",
        "reconstruction_verified": True,
        "llm_policy": "no_api",
        "candidate_derivation_inputs": [
            "action",
            "user",
            "work_lane_contract",
            "automation_liveness",
            "scheduler",
        ],
    }
    assert envelope["action_signature"]["matches"] is True
    assert (
        envelope["action_signature"]["source_hash"]
        == envelope["action_signature"]["envelope_hash"]
    )
    assert quota_action_signature_document(
        source
    ) == turn_envelope_action_signature_document(envelope)

    assert "agent_todo_summary" not in envelope
    assert "goal_frontier_projection" not in envelope
    assert "plan_summary" not in envelope
    assert envelope["compaction"]["source_json_bytes"] == len(
        json.dumps(source, ensure_ascii=False, separators=(",", ":"))
    )
    assert envelope["compaction"]["envelope_json_bytes"] < TURN_ENVELOPE_BUDGET_BYTES
    assert envelope["compaction"]["within_budget"] is True
    assert envelope["compaction"]["byte_reduction_ratio"] > 0.5
    assert envelope["compaction"]["envelope_json_bytes"] == len(
        json.dumps(envelope, ensure_ascii=False, separators=(",", ":"))
    )


def test_turn_envelope_preserves_signed_adaptive_orchestration_contract() -> None:
    source = _full_decision()
    source["task_orchestration_contract"] = {
        "schema_version": "task_orchestration_contract_v2",
        "mode": "adaptive",
        "coordinator_agent_id": "codex-fixture",
        "strategy_owner": "task_coordinator",
        "writeback_owner": "task_coordinator",
        "max_children": 2,
        "eligible_child_lanes": [
            {
                "todo_id": "todo_child001",
                "task_domain": "validation",
                "execution_kind": "ephemeral_child",
                "child_brief": {
                    "schema_version": "subagent_control_plane_handoff_v0",
                    "parent_goal_id": "fixture-goal",
                    "todo_id": "todo_child001",
                    "objective": "Validate one independent fixture.",
                    "task_domain": "validation",
                    "required_capabilities": [],
                    "task_repository": None,
                    "required_write_scopes": [],
                    "workspace_isolation": "not_required",
                    "context_policy": {
                        "selection_owner": "task_coordinator",
                        "default": "fresh",
                        "allowed": ["fresh"],
                    },
                    "expected_output": "public_safe_evidence",
                    "acceptance": ["report validation result and residual risk"],
                    "writeback_spend_contract": (
                        "child reports evidence only; task coordinator accepts evidence, "
                        "writes state, and spends once"
                    ),
                },
            }
        ],
        "blocked_lanes": [],
    }

    envelope = build_turn_envelope(source)

    assert envelope["task_orchestration_contract"] == source[
        "task_orchestration_contract"
    ]
    assert envelope["action_signature"]["matches"] is True
    assert quota_action_signature_document(
        source
    ) == turn_envelope_action_signature_document(envelope)


def test_three_long_child_briefs_stay_within_turn_envelope_budget() -> None:
    long_objective = "Validate " + "evidence " * 55
    items = [
        {
            "todo_id": "todo_primary",
            "status": "open",
            "task_class": "advancement_task",
            "action_kind": "implement",
            "task_domain": "code",
            "text": "Implement the primary slice.",
                "required_write_scopes": ["loopx/**"],
        },
        *[
            {
                "todo_id": f"todo_child_{index}",
                "status": "open",
                "task_class": "advancement_task",
                "action_kind": "validate",
                "task_domain": "validation",
                "text": long_objective,
            }
            for index in (1, 2, 3)
        ],
    ]
    summary = {"items": items}
    contract, _work_lane = apply_task_orchestration_contract(
        fallback_work_lane_contract={"lane": "advancement_task"},
        goal_boundary={
            "write_scope": ["loopx/**"],
            "orchestration": {
                "mode": "multi_subagent",
                "spawn_allowed": True,
                "max_children": 3,
                "allowed_domains": ["code", "validation"],
            }
        },
        agent_identity={
            "agent_id": "codex-fixture",
            "registered_agents": ["codex-fixture"],
        },
        agent_todo_summary=summary,
        raw_agent_todo_summary=summary,
        available_capabilities=["subagent_spawn", "subagent_resume"],
        parent_goal_id="fixture-goal",
    )
    source = _full_decision()
    source["task_orchestration_contract"] = contract

    envelope = build_turn_envelope(source)

    assert contract is not None
    assert len(contract["eligible_child_lanes"]) == 3
    assert envelope["action_signature"]["matches"] is True
    assert envelope["compaction"]["envelope_json_bytes"] < TURN_ENVELOPE_BUDGET_BYTES
    assert envelope["compaction"]["within_budget"] is True


def test_turn_envelope_full_decision_preserves_codex_app_profile() -> None:
    envelope = build_turn_envelope(
        _full_decision(),
        scheduler_execution_context=scheduler_execution_context_for_runtime_profile(
            SchedulerRuntimeProfile.CODEX_APP_HEARTBEAT
        ),
    )

    assert envelope["detail_ref"]["full_decision"] == (
        "loopx --format json quota should-run --goal-id fixture-goal "
        "--agent-id codex-fixture --codex-app"
    )


def test_turn_envelope_detail_refs_preserve_explicit_runtime_root() -> None:
    payload = _full_decision()
    payload["runtime_root"] = "/tmp/loopx custom runtime"

    envelope = build_turn_envelope(
        payload,
        scheduler_execution_context=scheduler_execution_context_for_runtime_profile(
            SchedulerRuntimeProfile.CODEX_CLI_VISIBLE
        ),
    )

    command_prefix = "loopx --runtime-root '/tmp/loopx custom runtime'"
    detail_ref = envelope["detail_ref"]
    assert detail_ref["full_decision"].startswith(
        f"{command_prefix} --format json quota should-run"
    )
    assert detail_ref["todo_detail"] == (
        f"{command_prefix} --format json todo list --goal-id fixture-goal"
    )
    assert detail_ref["status_detail"] == (
        f"{command_prefix} --format json status --goal-id fixture-goal"
    )


@pytest.mark.parametrize(
    ("profile", "expected_arg"),
    (
        (
            SchedulerRuntimeProfile.CODEX_CLI_VISIBLE,
            "--runtime-profile codex_cli",
        ),
        (
            SchedulerRuntimeProfile.CLAUDE_CODE_VISIBLE,
            "--runtime-profile claude_code",
        ),
        (
            SchedulerRuntimeProfile.GENERIC_CLI_AGENT_LOOP,
            "--runtime-profile generic_cli",
        ),
        (
            SchedulerRuntimeProfile.GENERIC_CLI_OUTER_CONTROLLER,
            "--runtime-profile outer_controller",
        ),
    ),
)
def test_turn_envelope_full_decision_compacts_first_class_profiles(
    profile: SchedulerRuntimeProfile,
    expected_arg: str,
) -> None:
    envelope = build_turn_envelope(
        _full_decision(),
        scheduler_execution_context=scheduler_execution_context_for_runtime_profile(
            profile
        ),
    )

    command = envelope["detail_ref"]["full_decision"]
    assert expected_arg in command
    assert " -H " not in command
    assert " -O " not in command
    assert " -M " not in command


def test_turn_envelope_unbound_full_decision_is_not_executable() -> None:
    full_decision = build_turn_envelope(_full_decision())["detail_ref"][
        "full_decision"
    ]

    assert full_decision == (
        "rerun the typed quota_guard from the current host packet"
    )
    assert "quota should-run" not in full_decision


def test_turn_envelope_preserves_exact_scheduler_ack_argv() -> None:
    source = _full_decision()
    capabilities = [
        "network",
        "github",
        "github_cli",
        "external_evidence_poll",
        "external_write",
        "lark_user",
        "lark_bot",
        "browser",
    ]
    cli_args = [
        "--registry",
        "/tmp/registry.global.json",
        "--runtime-root",
        "/tmp/runtime",
        "quota",
        "scheduler-ack-current",
        "--goal-id",
        "fixture-goal",
        "--agent-id",
        "codex-fixture",
    ]
    for capability in capabilities:
        cli_args.extend(["--available-capability", capability])
    cli_args.extend(
        [
            "--surface",
            "codex_app",
            "--state-key",
            "scheduler_hint.codex_app.stateful_backoff",
            "--applied-rrule",
            "FREQ=MINUTELY;INTERVAL=3",
            "--host-match-observed",
            "--reset-token",
            "reset-token",
            "--identity-signature",
            "identity-signature",
            "--execute",
        ]
    )
    source["scheduler_hint"]["codex_app"]["ack_hint"]["cli_args"] = cli_args

    envelope = build_turn_envelope(source)
    compact_args = envelope["scheduler"]["codex_app"]["ack_cli_args"]

    assert compact_args == cli_args
    assert compact_args.count("--available-capability") == len(capabilities)
    assert compact_args[-6:] == [
        "--host-match-observed",
        "--reset-token",
        "reset-token",
        "--identity-signature",
        "identity-signature",
        "--execute",
    ]


def test_turn_envelope_omits_oversized_scheduler_argv_instead_of_truncating() -> None:
    source = _full_decision()
    source["scheduler_hint"]["codex_app"]["ack_hint"]["cli_args"] = [
        "quota",
        "x" * 513,
        "--execute",
    ]

    envelope = build_turn_envelope(source)
    codex_app = envelope["scheduler"]["codex_app"]

    assert "ack_cli_args" not in codex_app
    assert codex_app["ack_cli_args_detail_ref"] == {
        "reason": "omitted_to_preserve_executable_argv",
        "request": "loopx quota should-run --include-detail scheduler",
    }


def test_turn_envelope_stays_actionable_during_scheduler_reset() -> None:
    source = _full_decision()
    todo_text = (
        "[P1] Continue host-neutral Agent CLI orchestration with start and resume, "
        "typed result, independent validation, repair or replan, exactly-once "
        "writeback and spend, and one real CLI end-to-end validation."
    )
    source["recommended_action"] = todo_text
    source["selected_todo"]["text"] = todo_text[:160].rstrip() + "..."
    source["interaction_contract"]["user_channel"] = {
        "action_required": False,
        "notify": "NOTIFY",
        "actions": ["Review an optional public documentation wording update."],
        "reason": "The optional review does not block the agent work lane.",
    }
    source["goal_boundary"].update(
        {
            "write_scope": [f"public/surface/{index}/**" for index in range(8)],
            "guards": [
                "stop before private material, credentials, destructive git, or "
                f"unauthorized production action {index}"
                for index in range(6)
            ],
        }
    )
    source["execution_profile"] = {
        "cadence": "bounded_progress_segment",
        "minimum_scale": "multi_surface_or_implementation",
        "spend_rule": "spend_only_after_artifact_validation_writeback",
        "must_include": ["coherent_artifact", "targeted_validation", "state_writeback"],
    }
    source["automation_liveness"]["pause_policy"] = (
        "pause only after a bounded repair or replan path is itself stuck for "
        "two more eligible turns"
    )
    source["vision_continuation_audit"] = {
        "schema_version": "vision_continuation_audit_v0",
        "required": True,
        "decision": "acceptance_gap_open",
        "selected_todo_is_goal_completion": False,
        "closeout_allowed_without_evidence": False,
        "required_before_closeout": [
            "derive requirements from the active vision and current todo",
            "name authoritative evidence for each requirement",
            "run bounded public research when local evidence is missing",
            "create a successor or replan trigger when acceptance remains unproven",
        ],
        "recommended_action": (
            "audit active vision acceptance before todo closeout and keep the vision "
            "active with a concrete successor when evidence remains incomplete"
        ),
    }
    capabilities = ["network", "shell", "filesystem_read", "filesystem_write"]
    ack_cli_args = [
        "--registry",
        "registry.json",
        "--runtime-root",
        ".runtime",
        "quota",
        "scheduler-ack-current",
        "--goal-id",
        "fixture-goal",
        "--agent-id",
        "codex-fixture",
    ]
    for capability in capabilities:
        ack_cli_args.extend(["--available-capability", capability])
    ack_cli_args.extend(
        [
            "--surface",
            "codex_app",
            "--state-key",
            "scheduler_hint.codex_app.stateful_backoff",
            "--applied-rrule",
            "FREQ=MINUTELY;INTERVAL=3",
            "--execute",
        ]
    )
    failure_cli_args = [
        *ack_cli_args[:4],
        "quota",
        "scheduler-fail-current",
        *ack_cli_args[6:-4],
        "--failed-rrule",
        "FREQ=MINUTELY;INTERVAL=3",
        "--codex-app-current-rrule",
        "FREQ=MINUTELY;INTERVAL=3",
        "--execute",
    ]
    codex_app = source["scheduler_hint"]["codex_app"]
    codex_app["ack_hint"]["cli_args"] = ack_cli_args
    codex_app["failure_hint"] = {"cli_args": failure_cli_args}
    source["protocol_action_packet"] = _legacy_protocol_packet(source)

    envelope = build_turn_envelope(source)
    compact_app = envelope["scheduler"]["codex_app"]

    assert envelope["action"]["selected_todo"]["text_ref"] == (
        "action.recommended_action"
    )
    assert "text" not in envelope["action"]["selected_todo"]
    assert compact_app["ack_cli_args"] == ack_cli_args
    assert "failure_cli_args" not in compact_app
    assert compact_app["failure_cli_args_detail_ref"] == {
        "reason": "cold_path_until_host_update_failure",
        "request": "loopx quota should-run --include-detail scheduler",
    }
    assert envelope["action_signature"]["matches"] is True
    assert envelope["compaction"]["within_budget"] is True
    assert envelope["compaction"]["envelope_json_bytes"] <= TURN_ENVELOPE_BUDGET_BYTES
    # Compression may create additional headroom; there is no minimum size.


def test_turn_envelope_keeps_concrete_user_gate() -> None:
    source = _full_decision()
    source["action_required"] = True
    source["open_count"] = 1
    source["interaction_contract"]["user_channel"] = {
        "action_required": True,
        "notify": "NOTIFY",
        "actions": ["Approve public release"],
        "reason": "release approval required",
    }

    envelope = build_turn_envelope(source)

    assert envelope["user"]["action_required"] is True
    assert envelope["user"]["actions"] == ["Approve public release"]
    assert envelope["user"]["reason"] == "release approval required"
    assert envelope["action_required"] is True
    assert envelope["open_count"] == 1
    assert envelope["action_signature"]["matches"] is True
    assert envelope["action_signature"]["coverage"] == (
        "turn_envelope_action_dimensions_v0"
    )


def test_action_signature_detects_semantic_drift() -> None:
    source = _full_decision()
    envelope = build_turn_envelope(source)
    envelope["writeback"]["spend_after_validation"] = False

    assert quota_action_signature_document(
        source
    ) != turn_envelope_action_signature_document(envelope)

    envelope = build_turn_envelope(source)
    envelope["execution_policy"]["safe_bypass_allowed"] = True

    assert quota_action_signature_document(
        source
    ) != turn_envelope_action_signature_document(envelope)

    envelope = build_turn_envelope(source)
    envelope["agent_id"] = "codex-other-peer"

    assert quota_action_signature_document(
        source
    ) != turn_envelope_action_signature_document(envelope)

    envelope = build_turn_envelope(source)
    envelope["action"]["selected_todo"]["continuation_policy"] = (
        "independent_handoff"
    )

    assert quota_action_signature_document(
        source
    ) != turn_envelope_action_signature_document(envelope)


def test_protocol_packet_derivation_keeps_only_real_residue() -> None:
    source = _compat_decision("residue")

    envelope = build_turn_envelope(source)
    packet = envelope["contract_capsule"]["protocol_action_packet"]

    assert packet["derivation_status"] == "verified_with_residue"
    assert packet["reconstruction_verified"] is True
    assert packet["residue"] == {"agent_action": "advance one product-path slice"}
    assert "summary" not in packet
    assert envelope["action_signature"]["matches"] is True


def test_protocol_packet_derivation_retains_unverified_summary() -> None:
    source = _compat_decision("opaque")

    envelope = build_turn_envelope(source)
    packet = envelope["contract_capsule"]["protocol_action_packet"]

    assert packet["derivation_status"] == "unverified_retain_summary"
    assert packet["reconstruction_verified"] is False
    assert packet["summary"] == "legacy opaque packet"


@pytest.mark.parametrize("path_segments", [170, 1_500])
def test_signed_host_action_preserves_a_long_complete_command(
    path_segments: int,
) -> None:
    source = _compat_decision("absent")
    command = (
        "loopx quota should-run --registry /"
        + "project/" * path_segments
        + " --codex-app"
    )
    assert len(command) > 1_200
    source["interaction_contract"]["agent_channel"]["primary_action"] = command

    envelope = build_turn_envelope(source)

    assert envelope["action_signature"]["matches"] is True
    assert envelope["action"]["primary_action"] == command
    assert extract_turn_authority({"turn_envelope": envelope})["primary_action"] == command
    if path_segments == 1_500:
        assert envelope["compaction"]["within_budget"] is False


@pytest.mark.parametrize("packet_format", ["absent", "historical_v0", "opaque", "residue"])
def test_protocol_packet_compatibility_through_real_readers(packet_format: str) -> None:
    """The summary is an observation; the typed decision owns execution."""
    source = _compat_decision(packet_format)
    before = deepcopy(source)
    turn = interpret_quota_should_run_packet(source)
    envelope = build_turn_envelope(source)
    authority = extract_turn_authority({"turn_envelope": envelope})

    assert source == before  # Reading does not rewrite the input packet.
    assert turn.observation.effective_action == "normal_run"
    assert turn.observation.should_run is True
    assert turn.interpretation.route == "advancement_task"
    assert list(turn.next_effect.cli_actions) == [
        "loopx refresh-state --goal-id fixture-goal --classification validated",
        "loopx quota spend-slot --goal-id fixture-goal --execute",
    ]
    assert turn.observation.protocol_summary == (
        None if packet_format == "absent" else source["protocol_action_packet"]["summary"]
    )
    assert authority["primary_action"] == (
        "a newer canonical action projection"
        if packet_format == "residue" else "advance one product-path slice"
    )
    assert authority["write_scope"] == ["loopx/**", "tests/**"]
    assert envelope["writeback"]["spend_allowed_now"] is False
    assert envelope["writeback"]["spend_after_validation"] is True
    assert envelope["execution_policy"]["safe_bypass_allowed"] is False
    assert quota_action_signature_document(source) == turn_envelope_action_signature_document(envelope)
    capsule = envelope["contract_capsule"]
    if packet_format == "absent":
        assert "protocol_action_packet" not in capsule
    else:
        assert capsule["protocol_action_packet"]["derivation_status"] == {
            "historical_v0": "verified",
            "opaque": "unverified_retain_summary",
            "residue": "verified_with_residue",
        }[packet_format]


def test_missing_packet_keeps_the_semantic_projection_and_signed_obligations() -> None:
    source = _compat_decision("absent")
    # This independently specified v0 wire example also exercises ordering.
    fields = protocol_action_packet_fields(source)
    assert fields["agent_action_required"] is True
    assert fields["quiet_noop_allowed"] is False
    assert render_protocol_action_packet_summary(fields) == HISTORICAL_V0_SUMMARY
    with_packet = _compat_decision("historical_v0")
    assert _legacy_protocol_packet(with_packet)["summary"] == HISTORICAL_V0_SUMMARY
    without_packet = build_turn_envelope(source)
    with_packet_envelope = build_turn_envelope(with_packet)
    # The only removed signed dimension is the capsule's packet witness.
    expected = turn_envelope_action_signature_document(with_packet_envelope)
    expected["contract_capsule"].pop("protocol_action_packet")
    assert turn_envelope_action_signature_document(without_packet) == expected


@pytest.mark.parametrize("user_required", [False, True], ids=["quiet-wait", "user-gate"])
def test_missing_protocol_packet_cannot_reopen_a_non_delivery_decision(user_required: bool) -> None:
    source = _compat_decision("absent")
    source.update(
        should_run=False, normal_delivery_allowed=False,
        effective_action="quota_skip", decision="skip",
        action_required=user_required, open_count=int(user_required),
    )
    source["execution_obligation"]["must_attempt_work"] = False
    source["work_lane_contract"]["must_attempt_work"] = False
    interaction = source["interaction_contract"]
    interaction["user_channel"].update(
        action_required=user_required, notify="NOTIFY" if user_required else "DONT_NOTIFY",
    )
    interaction["agent_channel"].update(
        must_attempt=False, delivery_allowed=False, quiet_noop_allowed=not user_required,
    )
    interaction["cli_channel"].update(
        next_cli_actions=[], spend_allowed_now=False, spend_after_validation=False,
    )
    envelope = build_turn_envelope(source)
    turn = interpret_quota_should_run_packet(source)
    assert turn.observation.should_run is False
    assert turn.observation.protocol_summary is None
    assert not turn.next_effect.cli_actions
    assert envelope["action"]["must_attempt"] is False
    assert envelope["action"]["delivery_allowed"] is False
    assert envelope["user"]["action_required"] is user_required
    assert envelope["action"]["quiet_noop_allowed"] is (not user_required)
    assert envelope["writeback"]["spend_after_validation"] is False
    assert envelope["writeback"]["spend_allowed_now"] is False


@pytest.mark.parametrize("packet_format", ["absent", "historical_v0", "opaque", "residue"])
@pytest.mark.parametrize("corruption", ["missing", "mismatch", "forged_equal_hashes", "action", "capsule"])
def test_protocol_packet_compatibility_does_not_bypass_host_signature_check(
    packet_format: str, corruption: str,
) -> None:
    envelope = build_turn_envelope(_compat_decision(packet_format))
    if corruption == "missing":
        envelope.pop("action_signature")
    elif corruption == "mismatch":
        envelope["action_signature"]["matches"] = False
    elif corruption == "forged_equal_hashes":
        envelope["action_signature"].update(
            source_hash="sha256:" + "0" * 64, envelope_hash="sha256:" + "0" * 64,
        )
    elif corruption == "action":
        envelope["action"]["primary_action"] = "perform an unsigned replacement action"
    else:
        envelope["contract_capsule"]["protocol_action_packet"] = {
            "schema_version": "protocol_action_packet_v0", "summary": "unsigned witness",
        }
    with pytest.raises(ValueError, match="action signature is missing or does not match"):
        extract_turn_authority({"turn_envelope": envelope})


@pytest.mark.parametrize("has_packet", [False, True])
def test_envelope_fallback_preserves_typed_failure_with_or_without_packet(has_packet: bool) -> None:
    from loopx.cli_commands.quota import _project_quota_cli_payload
    from argparse import Namespace

    failure: dict[str, Any] = {
        "ok": False, "decision": "skip", "should_run": False,
        "error_code": "scheduler_execution_context_invalid",
    }
    if has_packet:
        failure["protocol_action_packet"] = {
            "schema_version": "protocol_action_packet_v0", "summary": HISTORICAL_V0_SUMMARY,
        }
    before = deepcopy(failure)
    rendered = _project_quota_cli_payload(failure, Namespace(turn_envelope=True), frozenset(), None)
    assert "interaction_contract must be an object" in rendered.pop("turn_envelope_skipped")
    assert rendered == before
    assert failure == before


def test_protocol_packet_monitor_action_derives_without_residue() -> None:
    source = _full_decision()
    source["execution_obligation"]["must_attempt_work"] = False
    source["interaction_contract"]["mode"] = "monitor_quiet_skip"
    source["interaction_contract"]["agent_channel"].update(
        {
            "must_attempt": False,
            "delivery_allowed": False,
            "quiet_noop_allowed": True,
            "primary_action": "record at most one monitor poll, then stay quiet",
        }
    )
    source["work_lane_contract"].update(
        {
            "lane": "continuous_monitor",
            "obligation": "quiet_until_material_monitor_transition",
            "must_attempt_work": False,
        }
    )
    source["protocol_action_packet"] = _legacy_protocol_packet(source)

    envelope = build_turn_envelope(source)
    packet = envelope["contract_capsule"]["protocol_action_packet"]

    assert packet["derivation_status"] == "verified"
    assert packet["reconstruction_verified"] is True
    assert "residue" not in packet
    assert "summary" not in packet


def test_contract_capsule_stays_bounded_with_replan_and_vision_contracts() -> None:
    source = _full_decision()
    source["execution_profile"] = {
        "cadence": "bounded_progress_segment",
        "minimum_scale": "multi_surface_or_implementation",
        "spend_rule": "spend_only_after_artifact_validation_writeback",
        "must_include": ["coherent_artifact", "targeted_validation", "state_writeback"],
    }
    source["autonomous_replan_scope"] = {
        "schema_version": "autonomous_replan_scope_v0",
        "required": True,
        "applies": True,
        "scope": "explicit_agent_owner",
        "owner_agent_ids": ["codex-fixture"],
        "selected_peer_agent": "codex-fixture",
    }
    source["agent_scope_frontier"] = {
        "schema_version": "agent_scope_frontier_v0",
        "action": "successor_replan_required",
        "effective_action": "successor_replan_required",
        "blocks_delivery": True,
        "quiet_noop_allowed": False,
        "requires_replan": True,
        "recommended_action": "write a concrete successor before quiet wait " * 20,
        "spend_policy": "spend only after successor writeback " * 20,
    }
    source["vision_continuation_audit"] = {
        "schema_version": "vision_continuation_audit_v0",
        "required": True,
        "decision": "acceptance_gap_open",
        "selected_todo_is_goal_completion": False,
        "closeout_allowed_without_evidence": False,
        "required_before_closeout": [
            f"requirement-{index}-" + "evidence " * 30 for index in range(4)
        ],
        "recommended_action": "audit active vision acceptance " * 30,
    }
    source["automation_liveness"]["pause_policy"] = (
        "pause only after bounded repair is stuck " * 20
    )

    envelope = build_turn_envelope(source)

    assert envelope["action_signature"]["matches"] is True
    assert envelope["contract_capsule"]["autonomous_replan_scope"]["applies"] is True
    assert (
        envelope["contract_capsule"]["agent_scope_frontier"]["requires_replan"] is True
    )
    assert envelope["contract_capsule"]["vision_continuation_audit"]["required"] is True
    assert envelope["compaction"]["within_budget"] is True
    assert envelope["compaction"]["envelope_json_bytes"] < TURN_ENVELOPE_BUDGET_BYTES


def test_turn_envelope_retains_configured_cadence_floor_and_host_boundary() -> None:
    source = _full_decision()
    app = source["scheduler_hint"]["codex_app"]
    policy = {"min_interval_minutes": 1440, "configuration_revision": 3,
              "enforcement": "scheduler_recommendation"}
    guarantee = {"pre_model_atomic_admission": "not_qualified",
                 "model_wakeup_tokens_prevented": False}
    app["execution_interval_policy"] = policy
    app["guarantee"] = guarantee
    envelope = build_turn_envelope(source)
    projected = envelope["scheduler"]["codex_app"]
    assert projected["execution_interval_policy"] == policy
    assert projected["guarantee"] == guarantee
