"""Settlement remains executable and signed through the opt-in compact view."""
from copy import deepcopy

import pytest

from loopx.control_plane.quota.turn_envelope import (
    build_turn_envelope,
    quota_action_signature_document,
    turn_envelope_action_signature_document,
)
from tests.test_turn_envelope import _full_decision
from tests.control_plane.test_quota_settlement_cli import (
    AGENT_ID, GOAL_ID, TODO_ID, TURN_ID,
    _configure_read_only_todo, _run_cli, _run_generated_cli,
    _spend_run_count, _write_fixture,
)


def _plan():
    # Independent wire example, not generated by the projection under test.
    return {
        "schema_version": "quota_settlement_plan_v1",
        "identity": {
            "schema_version": "quota_settlement_identity_v0",
            "goal_id": "fixture-goal", "agent_id": "codex-fixture",
            "todo_id": "todo_fixture0001", "turn_instance_id": "turn-original",
            "effect_id": "fixture-goal:codex-fixture:todo_fixture0001:turn-original",
        },
        "ordered_steps": [
            {"kind": "validation", "owner": "agent", "command_condition": "todo_deliverable_complete"},
            {"kind": "durable_writeback", "owner": "agent", "precondition": "validation succeeded"},
            {"kind": "quota_spend", "owner": "agent", "expected_receipt": "quota_spend_receipt"},
            {"kind": "terminal_closeout", "owner": "agent", "conditional": True},
        ],
        "host_handoff": {"owner": "host", "kind": "scheduler_handoff", "inside_agent_settlement": False},
    }


def test_plan_and_long_commands_survive_without_mutating_cached_packet():
    source = _full_decision()
    cli = source["interaction_contract"]["cli_channel"]
    cli["settlement_plan"] = _plan()
    command = "loopx --runtime-root /" + "nested/" * 80 + " quota spend-slot --turn-instance-id turn-original --execute"
    cli["next_cli_actions"] = [command]
    cli["settlement_plan"]["ordered_steps"][2]["command_template"] = command
    before = deepcopy(source)
    envelope = build_turn_envelope(source)
    assert source == before
    assert envelope["writeback"]["settlement_plan"] == before["interaction_contract"]["cli_channel"]["settlement_plan"]
    assert envelope["writeback"]["next_cli_actions"] == [command]
    assert envelope["action_signature"]["coverage"] == "turn_envelope_action_dimensions_v5"
    assert quota_action_signature_document(source) == turn_envelope_action_signature_document(envelope)


@pytest.mark.parametrize("mutation", ["identity", "order", "condition", "receipt", "handoff", "remove"])
def test_signature_rejects_settlement_semantic_loss(mutation):
    source = _full_decision()
    source["interaction_contract"]["cli_channel"]["settlement_plan"] = _plan()
    envelope = build_turn_envelope(source)
    plan = envelope["writeback"]["settlement_plan"]
    if mutation == "identity":
        plan["identity"]["effect_id"] = "another-turn"
    elif mutation == "order":
        plan["ordered_steps"].reverse()
    elif mutation == "condition":
        plan["ordered_steps"][-1]["conditional"] = False
    elif mutation == "receipt":
        plan["ordered_steps"][2]["expected_receipt"] = "validation_receipt"
    elif mutation == "handoff":
        plan["host_handoff"]["inside_agent_settlement"] = True
    else:
        del envelope["writeback"]["settlement_plan"]
    assert quota_action_signature_document(source) != turn_envelope_action_signature_document(envelope)


def test_absent_plan_is_not_invented_for_historical_or_unbound_packets():
    source = _full_decision()
    before = build_turn_envelope(source)
    assert "settlement_plan" not in before["writeback"]
    assert before["action_signature"]["coverage"] == "turn_envelope_action_dimensions_v0"
    source["interaction_contract"]["cli_channel"].update(
        selection_required=True, next_cli_actions=[], spend_after_validation=False,
    )
    envelope = build_turn_envelope(source)
    assert "settlement_plan" not in envelope["writeback"]
    assert envelope["writeback"]["spend_after_validation"] is False


def test_real_cli_envelope_settles_original_turn_once(tmp_path):
    project, runtime, registry = _write_fixture(tmp_path)
    _configure_read_only_todo(project)
    args = ("quota", "should-run", "--codex-app", "--goal-id", GOAL_ID,
            "--agent-id", AGENT_ID, "--todo-id", TODO_ID,
            "--turn-instance-id", TURN_ID, "--scan-path", str(project))
    rc, full = _run_cli(registry, runtime, *args)
    assert rc == 0, full
    rc, envelope = _run_cli(registry, runtime, *args, "--turn-envelope")
    assert rc == 0, envelope
    plan = envelope["writeback"]["settlement_plan"]
    assert plan == full["interaction_contract"]["cli_channel"]["settlement_plan"]
    assert plan["identity"] == full["heartbeat_receipt"]["settlement_identity"]
    assert [step["kind"] for step in plan["ordered_steps"]] == [
        "validation", "durable_writeback", "quota_spend", "terminal_closeout",
    ]
    assert plan["ordered_steps"][-1]["conditional"] is True
    assert plan["host_handoff"]["inside_agent_settlement"] is False
    spend_command = plan["ordered_steps"][2]["command_template"].replace("loopx ", "loopx --format json ", 1)
    rc, premature = _run_generated_cli(spend_command, registry_path=registry)
    assert rc != 0, premature
    assert _spend_run_count(runtime) == 0
    writeback = plan["ordered_steps"][1]["command_template"].replace("loopx ", "loopx --format json ", 1)
    # A validated exclusion advances research without claiming the objective is met.
    # The same negative result is not a blocker merely because a candidate failed.
    guidance = plan["ordered_steps"][1]["precondition"]
    assert "Route elimination needs evidence" in guidance
    assert "failure alone is not progress" in guidance
    observation_only = writeback.replace("<validated_progress>", "validated_exclusion").replace(
        "<scale>", "single_surface").replace("<outcome>", "surface_only")
    rc, rejected_observation = _run_generated_cli(
        observation_only + " --progress-result-class unchanged"
        " --no-global-sync --suppress-external-sinks", registry_path=registry,
    )
    assert rc != 0, rejected_observation
    assert _spend_run_count(runtime) == 0
    invalid = writeback.replace("<validated_progress>", "validated_exclusion").replace(
        "<scale>", "single_surface").replace("<outcome>", "outcome_gap")
    rc, rejected = _run_generated_cli(
        invalid + " --progress-result-class advanced --progress-evidence-id exclusion-proof"
        " --no-global-sync --suppress-external-sinks", registry_path=registry,
    )
    assert rc != 0, rejected
    assert "requires --progress-result-class blocked" in rejected["error"]
    assert _spend_run_count(runtime) == 0
    writeback = writeback.replace("<validated_progress>", "validated_exclusion").replace(
        "<scale>", "single_surface").replace("<outcome>", "outcome_progress")
    writeback += " --progress-result-class advanced --progress-evidence-id exclusion-proof"
    rc, refreshed = _run_generated_cli(
        writeback + " --delivery-boundary in_flight_continuation --no-global-sync --suppress-external-sinks",
        registry_path=registry,
    )
    assert rc == 0, refreshed
    for replay in (False, True):
        rc, spent = _run_generated_cli(spend_command, registry_path=registry)
        assert rc == 0, spent
        assert spent["settlement_result"]["ok"] is True
        if replay:
            assert spent["idempotent_replay"] is True
    assert _spend_run_count(runtime) == 1
