from copy import deepcopy
from hashlib import sha256
import json

import pytest
from todo_frontier_fixture import summary_frontier_index

from loopx.control_plane import effect_runtime
from loopx.control_plane.goals.goal_frontier.long_todo_chain import (
    long_todo_chain_successor_checkpoints,
)


def rows():
    return [
        {"todo_id": "todo_aaa", "task_class": "advancement_task", "status": "open",
         "text": "验证边界", "updated_at": "2026-09-01T00:00:00.000001Z"},
        {"todo_id": "todo_bbb", "task_class": "advancement_task", "status": "open",
         "text": "Independent work", "excluded_agents": ["worker-a"],
         "updated_at": "2026-09-01T00:00:00.000002Z"},
    ]


@pytest.mark.parametrize("index", [None, [], "invalid", 1, True])
def test_summary_adapter_rejects_non_object_batched_frontier(monkeypatch, index):
    original = effect_runtime.effect_runtime_result

    def invalid_frontier(method, request, **kwargs):
        result = original(method, request, **kwargs)
        if method == "todo.summary.project":
            result["fields"]["advancement_frontier_revision_index"] = index
        return result

    monkeypatch.setattr(effect_runtime, "effect_runtime_result", invalid_frontier)
    with pytest.raises(ValueError, match="invalid typed Todo summary frontier index"):
        summary_frontier_index(rows())


def test_excluded_unclaimed_work_does_not_rearm_this_agents_frontier():
    before = rows()
    after = deepcopy(before)
    after[1]["priority"] = "P0"
    after[1]["updated_at"] = "2026-09-02T00:00:00Z"
    before_index = summary_frontier_index(before)
    after_index = summary_frontier_index(after)
    assert before_index["by_agent"] == after_index["by_agent"]
    assert before_index["unclaimed"] != after_index["unclaimed"]
    # The excluded-only lane must remain explicit even without claimed work.
    assert before_index["by_agent"][0]["agent_id"] == "worker-a"
    assert before_index["by_agent"][0]["complete"] is True


def test_duplicate_identity_cannot_be_a_complete_frontier():
    source = rows()
    source[1]["todo_id"] = source[0]["todo_id"]
    with pytest.raises(effect_runtime.EffectRuntimeRejected, match="duplicate succession identity"):
        summary_frontier_index(source)


def test_removing_exclusion_rearms_newly_available_work():
    source = rows()
    before = summary_frontier_index(source)
    source[1].pop("excluded_agents")
    after = summary_frontier_index(source)
    assert after["by_agent"] == []
    assert before["by_agent"][0]["frontier_revision"] != after["unclaimed"]["frontier_revision"]


def test_summary_frontier_preserves_unicode_hash_and_microsecond_ordering():
    # Explicit protocol records, not output generated by the implementation.
    material = [{"status": "open", "done": False, "task_class": "advancement_task", "text": "边界 🧭",
                 "todo_id": "todo_aaa"},
                {"status": "done", "done": True, "task_class": "advancement_task", "text": "", "todo_id": "todo_bbb"}]
    encoded = json.dumps(material, ensure_ascii=True, separators=(",", ":"), sort_keys=True)
    expected = "todo_frontier_revision_v0:" + sha256(encoded.encode()).hexdigest()[:24]
    source = [{**material[1], "completed_at": "2026-09-01T08:00:00.000001+08:00"},
              {**material[0], "updated_at": "2026-09-01T00:00:00.000002Z"}]
    checkpoint = summary_frontier_index(source)["all"]
    assert checkpoint["complete"] is True
    assert checkpoint["frontier_revision"] == expected
    assert checkpoint["frontier_updated_at"] == "2026-09-01T00:00:00.000002Z"


def test_legacy_agent_spelling_in_index_remains_readable():
    source = rows()[:1]
    source[0]["claimed_by"] = "Worker A"
    index = summary_frontier_index(source)
    index["by_agent"][0]["agent_id"] = " Worker\u0085A "
    result = long_todo_chain_successor_checkpoints(
        source, agent_id="worker-a", triggers=[], obligation_id="replan-test",
        candidates=[], frontier_revision_index=index,
    )
    assert result is not None
    assert result["trigger_checkpoints"][0]["frontier_revision"] == index["by_agent"][0]["frontier_revision"]


def test_large_frontier_transport_preserves_exact_v0_identity_and_tail_edits():
    material = [{"todo_id": f"todo_{index:04}", "status": "open", "done": False, "task_class": "advancement_task",
                 "text": ("Complete synthetic description " * 40).rstrip()} for index in range(2500)]
    encoded = json.dumps(material, ensure_ascii=True, separators=(",", ":"), sort_keys=True)
    assert len(encoded.encode()) > 2 * 1024 * 1024
    expected = "todo_frontier_revision_v0:" + sha256(encoded.encode()).hexdigest()[:24]
    source = [{**item, "updated_at": "2026-09-01T00:00:00Z"} for item in material]
    checkpoint = summary_frontier_index(source)["all"]
    assert checkpoint["complete"] is True
    assert checkpoint["frontier_revision"] == expected
    assert checkpoint["frontier_updated_at"] == "2026-09-01T00:00:00Z"
    source[-1]["text"] += " Material edit at the tail."
    assert summary_frontier_index(source)["all"]["frontier_revision"] != expected
