from copy import deepcopy
from hashlib import sha256
import json

import pytest

from loopx.control_plane.todos import frontier_revision
from loopx.control_plane.goals.goal_frontier.long_todo_chain import (
    long_todo_chain_successor_checkpoints,
)

from loopx.control_plane.todos.frontier_revision import (
    build_advancement_frontier_revision_index,
)


def rows():
    return [
        {"todo_id": "todo_a", "task_class": "advancement_task", "status": "open",
         "text": "验证边界", "updated_at": "2026-09-01T00:00:00.000001Z"},
        {"todo_id": "todo_b", "task_class": "advancement_task", "status": "open",
         "text": "Independent work", "excluded_agents": ["worker-a"],
         "updated_at": "2026-09-01T00:00:00.000002Z"},
    ]


@pytest.mark.parametrize("index", [None, [], "invalid", 1, True])
def test_index_adapter_rejects_non_object_typed_response(monkeypatch, index):
    monkeypatch.setattr(frontier_revision, "effect_runtime_result",
                        lambda *_args: {"index": index})
    with pytest.raises(TypeError, match="typed frontier revision response index must be an object"):
        build_advancement_frontier_revision_index(rows())


def test_excluded_unclaimed_work_does_not_rearm_this_agents_frontier():
    before = rows()
    after = deepcopy(before)
    after[1]["priority"] = "P0"
    after[1]["updated_at"] = "2026-09-02T00:00:00Z"
    before_index = build_advancement_frontier_revision_index(before)
    after_index = build_advancement_frontier_revision_index(after)
    assert before_index["by_agent"] == after_index["by_agent"]
    assert before_index["unclaimed"] != after_index["unclaimed"]
    # The excluded-only lane must remain explicit even without claimed work.
    assert before_index["by_agent"][0]["agent_id"] == "worker-a"
    assert before_index["by_agent"][0]["complete"] is True


def test_duplicate_identity_cannot_be_a_complete_frontier():
    source = rows()
    source[1]["todo_id"] = source[0]["todo_id"]
    index = build_advancement_frontier_revision_index(source)
    assert index["all"] == index["unclaimed"] == {"complete": False}


def test_removing_exclusion_rearms_newly_available_work():
    source = rows()
    before = build_advancement_frontier_revision_index(source)
    source[1].pop("excluded_agents")
    after = build_advancement_frontier_revision_index(source)
    assert after["by_agent"] == []
    assert before["by_agent"][0]["frontier_revision"] != after["unclaimed"]["frontier_revision"]


def test_v0_codec_preserves_unicode_hash_and_microsecond_ordering():
    # Explicit protocol records, not output generated by the implementation.
    material = [{"status": "open", "task_class": "advancement_task", "text": "边界 🧭",
                 "todo_id": "todo_a"},
                {"status": "done", "task_class": "advancement_task", "todo_id": "todo_b"}]
    encoded = json.dumps(material, ensure_ascii=True, separators=(",", ":"), sort_keys=True)
    expected = "todo_frontier_revision_v0:" + sha256(encoded.encode()).hexdigest()[:24]
    source = [{**material[1], "completed_at": "2026-09-01T08:00:00.000001+08:00"},
              {**material[0], "updated_at": "2026-09-01T00:00:00.000002Z"}]
    checkpoint = build_advancement_frontier_revision_index(source)["all"]
    assert checkpoint["complete"] is True
    assert checkpoint["frontier_revision"] == expected
    assert checkpoint["frontier_updated_at"] == "2026-09-01T00:00:00.000002Z"


def test_legacy_agent_spelling_in_index_remains_readable():
    source = rows()[:1]
    source[0]["claimed_by"] = "Worker A"
    index = build_advancement_frontier_revision_index(source)
    index["by_agent"][0]["agent_id"] = " Worker\u0085A "
    result = long_todo_chain_successor_checkpoints(
        source, agent_id="worker-a", triggers=[], obligation_id="replan-test",
        candidates=[], frontier_revision_index=index,
    )
    assert result is not None
    assert result["trigger_checkpoints"][0]["frontier_revision"] == index["by_agent"][0]["frontier_revision"]


def test_large_frontier_transport_preserves_exact_v0_identity_and_tail_edits():
    material = [{"todo_id": f"todo_{index:04}", "task_class": "advancement_task",
                 "text": "Complete synthetic description " * 40} for index in range(2500)]
    encoded = json.dumps(material, ensure_ascii=True, separators=(",", ":"), sort_keys=True)
    assert len(encoded.encode()) > 2 * 1024 * 1024
    expected = "todo_frontier_revision_v0:" + sha256(encoded.encode()).hexdigest()[:24]
    source = [{**item, "updated_at": "2026-09-01T00:00:00Z"} for item in material]
    checkpoint = build_advancement_frontier_revision_index(source)["all"]
    assert checkpoint["complete"] is True
    assert checkpoint["frontier_revision"] == expected
    assert checkpoint["frontier_updated_at"] == "2026-09-01T00:00:00Z"
    source[-1]["text"] += " Material edit at the tail."
    assert build_advancement_frontier_revision_index(source)["all"]["frontier_revision"] != expected
