let state = {goals:[],members:[],lessons:[],settings:{},connections:{}}, view='overview', selected='', tab='work';
let conversation=null;
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=s=>s?new Date(typeof s==='number'?s*1000:s).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}):'尚未检查';
const kind={supplement:'补充',execute:'执行',judge:'判断'}, phases={awaiting:'等待回应',submitted:'待 AI 验收',gap:'需要补充',verified:'已验收'};
const person=id=>state.members.find(m=>m.id===id)?.name||'待匹配成员';
function toast(message){$('#toast').textContent=message;$('#toast').style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').style.display='none',6000)}
async function api(route,data){const r=await fetch(route,{method:'POST',headers:{'Content-Type':'application/json','X-Team-Workspace':'local'},body:JSON.stringify(data)});const j=await r.json();if(!r.ok)throw Error(j.error||'操作失败');return j.result}
async function refresh(){try{const r=await fetch('/api/state');if(!r.ok)throw Error('服务未响应');const next=await r.json(),changed=JSON.stringify(state)!==JSON.stringify(next);state=next;$('#host-status').textContent=state.active_goal?'AI 正在推进':'本地服务运行中';if(changed||!$('#content').children.length)render()}catch(e){$('#host-status').textContent='服务连接中断';}}
function button(action,label,extra='',cls=''){return `<button data-action="${action}" ${extra} class="${cls}">${label}</button>`}
function empty(title,body,action=''){return `<div class="empty"><div class="symbol">↗</div><h2>${title}</h2><p>${body}</p>${action}</div>`}
function page(title,desc,action=''){return `<div class="page-head"><div><div class="eyebrow">TEAM WORKSPACE</div><h1>${title}</h1><p>${desc}</p></div>${action}</div>`}
function status(g){return g.last_error?'需要处理':!g.enabled?'已暂停':state.active_goal===g.id?'AI 正在推进':g.requests.some(r=>r.phase!=='verified')?'等待人类贡献':'持续推进中'}
function goalCard(g){const done=g.todos.filter(t=>t.role==='agent'&&t.done&&t.host_verified).length,open=g.todos.filter(t=>t.role==='agent'&&!t.done).length;return `<article class="card goal-card" tabindex="0" role="button" data-goal="${g.id}"><div class="card-top"><span class="eyebrow">${esc(g.horizon)}</span><span class="badge ${g.last_error?'error':''}">${status(g)}</span></div><h2>${esc(g.title)}</h2><p>${esc(g.objective.slice(0,170))}</p><p class="section-note">${esc(g.activity)}</p><div class="card-footer"><span>${done} 项已验证 · ${open} 项推进中</span><span>查看目标 →</span></div></article>`}
function overview(){const requests=state.goals.flatMap(g=>g.requests).filter(r=>r.phase!=='verified');return page('给出方向，让 AI 持续推进','目标、执行、人的贡献与反馈，在同一条工作线上。',button('new-goal','＋ 新建业务目标','','primary'))+`<div class="metrics"><div class="metric"><strong>${state.goals.filter(g=>g.enabled).length}</strong><span>正在推进的目标</span></div><div class="metric"><strong>${requests.length}</strong><span>需要人类贡献</span></div><div class="metric"><strong>${state.goals.flatMap(g=>g.todos).filter(t=>t.role==='agent'&&t.done&&t.host_verified).length}</strong><span>已验证的任务</span></div></div>`+(state.goals.length?`<div class="grid">${state.goals.map(goalCard).join('')}</div>`:empty('从一个业务方向开始','描述你希望达成的结果和边界。AI 会滚动拆解工作，在需要你的时候带着具体问题回来。',button('new-goal','描述我的目标','','primary')))}
function requestCard(r,goalTitle=''){return `<article class="card request"><div class="card-top"><span class="badge wait">需要${kind[r.kind]}</span><small>${phases[r.phase]}</small></div><h2>${esc(r.title)}</h2>${goalTitle?`<p class="section-note">${esc(goalTitle)}</p>`:''}<p class="pre">${esc(r.reason)}</p><div class="expected"><b>期待的贡献</b><p class="pre">${esc(r.expected)}</p></div><div class="task-meta"><span>${esc(person(r.member_id))}</span><span>${r.parent_todo_id?'关联任务等待中':'其他工作可继续'}</span></div>${r.responses.slice(-2).map(x=>`<div class="reply"><b>${x.kind==='correction'?'纠正':x.kind==='decision'?'判断':'回应'}</b><p class="pre">${esc(x.text)}</p></div>`).join('')}${r.evidence.length?`<p class="section-note">${r.evidence.length} 条候选证据 · ${r.evidence.filter(e=>e.source==='airjelly').length} 条行为记录</p>`:''}${r.gap?`<div class="gap">${esc(r.gap)}</div>`:''}${r.phase==='verified'?`<p class="success">✓ ${esc(r.verification?.reason||'已验收')}</p>`:`<div class="actions feedback-box">${button('respond','回应 / 纠正',`data-id="${r.id}"`,'primary')}${button('upload','提交文件',`data-id="${r.id}" data-goal-id="${r.goal_id}"`)}</div>`}</article>`}
function needs(){const local=state.settings.local_member_id;const rows=state.goals.flatMap(g=>g.requests.filter(r=>r.phase!=='verified'&&(!local||!r.member_id||r.member_id===local)).map(r=>[r,g.title]));return page('需要我','AI 已准备背景和预期产出。你可以补充、执行、判断，也可以纠正任务。')+(rows.length?`<div class="grid">${rows.map(([r,t])=>requestCard(r,t)).join('')}</div>`:empty('暂时没有需要你的事情','AI 会继续处理可独立推进的工作。'))}
function taskRow(t,g){const detail=g.tasks.find(x=>x.id===t.todo_id);return `<div class="task"><div class="row"><h3>${t.done?'✓ ':''}${esc(t.text)}</h3><span class="badge ${t.status==='deferred'?'wait':''}">${g.running_todo===t.todo_id&&state.active_goal===g.id?'AI 执行 / 验收中':(t.host_verified?'已验证':({open:'待执行',done:'已完成',deferred:'等待贡献',blocked:'受阻'})[t.status])||esc(t.status)}</span></div>${detail?`<p>${esc(detail.acceptance)}</p>`:''}${t.note&&t.note!==detail?.acceptance?`<p>${esc(t.note)}</p>`:''}</div>`}
function monitorCard(m,g){const todo=g.todos.find(t=>t.todo_id===m.id)||{};return `<article class="card"><div class="card-top"><h3>${esc(todo.text)}</h3><span class="badge">${todo.status==='blocked'?'已暂停':todo.expires_at&&new Date(todo.expires_at)<new Date()?'已到期':'监测中'}</span></div><p>每 ${esc(todo.cadence)} 检查 · 下次 ${date(todo.next_due_at)}</p><p class="section-note">${esc(m.path)}<br>上次检查 ${date(m.last_checked)}${todo.expires_at?'<br>结束于 '+date(todo.expires_at):''}</p><p>${esc(m.last_summary||'等待建立观测基线')}</p><div class="actions">${button('monitor-run','立即检查',`data-id="${m.id}" data-goal-id="${g.id}"`)}${button('monitor-toggle',todo.status==='blocked'?'恢复':'暂停',`data-id="${m.id}" data-goal-id="${g.id}" data-operation="${todo.status==='blocked'?'resume':'pause'}"`)}</div></article>`}
function detail(){const g=state.goals.find(g=>g.id===selected);if(!g)return overview();const requests=g.requests.filter(r=>r.phase!=='verified');let body='';if(tab==='work'){body=g.todos.filter(t=>t.role==='agent'&&t.task_class!=='continuous_monitor').map(t=>taskRow(t,g)).join('')||'<p class="muted">AI 将根据目标生成具体任务。</p>';body=`<section class="card"><h2>AI 的执行计划</h2>${body}</section>${requests.map(r=>requestCard(r)).join('')}`;}else if(tab==='monitors'){body=button('new-monitor','＋ 添加监测',`data-goal-id="${g.id}"`)+(g.monitors.length?g.monitors.map(m=>monitorCard(m,g)).join(''):empty('让外部反馈影响计划','第一版支持监测工作目录内的指标或反馈文件。文件有变化时，AI 会评估影响并创建后续任务。'));}else{body=g.requests.length?g.requests.map(r=>requestCard(r)).join(''):empty('还没有人类调用','只有需要补充、执行或判断时，AI 才会发起调用。');}return page(esc(g.title),esc(g.activity),`<div class="actions">${button('goal-toggle',g.enabled?'暂停推进':'恢复推进',`data-id="${g.id}" data-enabled="${!g.enabled}"`)}${button('feedback','补充目标反馈',`data-id="${g.id}"`,'primary')}</div>`)+(g.last_error||g.projection_error?`<div class="error-box">${esc(g.last_error||g.projection_error)}</div>`:'')+`<div class="tabs">${[['work','执行与协作'],['humans','人类调用'],['monitors','反馈监测']].map(([id,name])=>`<button class="${tab===id?'active':''}" data-tab="${id}">${name}</button>`).join('')}</div><div class="detail-grid"><div class="stack">${body}</div><div class="stack"><section class="card"><div class="eyebrow">${esc(g.horizon)}</div><h2>目标与成功标准</h2>${state.native_dashboard_url?`<a class="file-link" target="_blank" rel="noopener" href="${esc(state.native_dashboard_url)}?goalId=${encodeURIComponent(g.id)}&statusUrl=%2Fstatus.json">打开 LoopX 原生 Goal 对话 ↗</a>`:''}<p class="pre">${esc(g.objective)}</p><div class="divider"></div><h3>如何判断有进展</h3><p class="pre">${esc(g.acceptance)}</p><h3>执行边界</h3><p class="section-note pre">${esc(g.boundaries)}</p></section><section class="card"><h2>成果文件</h2>${(g.artifacts||[]).length?`<div class="stack">${g.artifacts.map(p=>`<a class="file-link" href="/api/artifact?goal=${encodeURIComponent(g.id)}&path=${encodeURIComponent(p)}">↓ ${esc(p)}</a>`).join('')}</div>`:'<p class="section-note">通过验收的文件会出现在这里。</p>'}<div class="divider"></div><h2>工作进程</h2><ol class="timeline">${[...g.events].reverse().slice(0,18).map(e=>`<li><time>${date(e.at)}</time><p class="pre">${esc(e.text)}</p></li>`).join('')}</ol></section></div></div>`}
function members(){return page('团队成员','描述能力与判断范围，让 AI 把必要的贡献交给合适的人。',button('new-member','＋ 添加成员','','primary'))+(state.members.length?`<div class="grid">${state.members.map(m=>`<article class="card"><div class="card-top"><div class="connection"><span class="member-avatar">${esc(m.name[0])}</span><div><h3>${esc(m.name)}</h3><small>${esc(m.role)}</small></div></div>${button('edit-member','编辑',`data-id="${m.id}"`,'compact')}</div><p class="pre">${esc(m.description)}</p>${(state.jobs||[]).filter(j=>j.member_id===m.id).slice(-1).map(j=>`<p class="section-note">能力提取：${({queued:'排队中',done:'已完成',failed:'未完成'})[j.phase]} ${esc(j.error||'')}</p>`).join('')}<div class="tags">${m.skills.map(s=>`<span class="badge">${esc(s)}</span>`).join('')}</div><p class="section-note">可判断的范围：${esc(m.decision_scopes.join('、')||'尚未声明')}</p>${state.capabilities.filter(c=>c.member_id===m.id).map(c=>`<div class="expected"><small>行为记录推断 · 可纠正</small><p>${esc(c.text)}</p></div>`).join('')}<div class="actions">${button('infer','从已同步记录提取能力线索',`data-id="${m.id}"`,'compact')}</div></article>`).join('')}</div>`:empty('先认识一起工作的人','可以从你自己的职位、能力和判断范围开始。',button('new-member','添加我的能力','','primary')))}
function learning(){return page('反馈与经验','每一次纠正都保留来源和适用范围，供 AI 在后续同类工作中参考。')+(state.lessons.length?state.lessons.map(l=>`<article class="card lesson ${l.active?'':'disabled'}"><div class="card-top"><span class="badge">${l.active?'使用中':'已停用'}</span><small>${date(l.at)}</small></div><p class="pre">${esc(l.text)}</p><p class="section-note">适用目标：${esc(state.goals.find(g=>g.id===l.goal_id)?.title||'当前目标')} · 成员：${esc(person(l.member_id))} · 能力：${esc(l.skill||'本次调用')}</p><div class="actions">${button('edit-lesson','编辑',`data-id="${l.id}"`)}${button('toggle-lesson',l.active?'停用':'启用',`data-id="${l.id}" data-enabled="${!l.active}"`)}</div></article>`).join(''):empty('经验来自真实的纠正','当你觉得 AI 调用人的方式、时机或任务内容不合适，可以在回应中选择“纠正”。'))}
function settings(){const c=state.connections;return page('连接与设置','分别验证执行能力和行为记录来源。')+`<div class="grid">${[['codex','Codex','⌘','本机执行与独立验收'],['airjelly','AirJelly','◉','读取经过授权的本机行为记录']].map(([id,name,icon,desc])=>`<section class="card"><div class="card-top"><div class="connection"><span class="icon">${icon}</span><h2>${name}</h2></div><span class="badge ${c[id]?.available?'':'wait'}">${c[id]?.available?'已验证':'未验证'}</span></div><p>${desc}</p><p class="section-note">${esc(c[id]?.detail||'尚未检查')}</p>${button('check','检查连接',`data-provider="${id}"`)}</section>`).join('')}</div><section class="card feedback-box"><h2>持续运行设置</h2><p class="section-note">服务运行时自动推进。开启 AirJelly 后，每 30 秒增量读取行为记录，并为该成员未结束的调用提供候选证据。</p>${button('settings','调整设置')}<p>行为记录：${state.settings.airjelly_enabled?'已开启':'未开启'} · 本机成员：${esc(person(state.settings.local_member_id))}</p><p>24 小时模型调用上限：${state.settings.daily_model_calls}</p></section>`}
function render(){const count=state.goals.flatMap(g=>g.requests).filter(r=>r.phase!=='verified').length;$('#needs-count').textContent=count;document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$('#breadcrumb').textContent='团队工作台 / '+({overview:'目标总览',needs:'需要我',members:'团队成员',learning:'反馈与经验',settings:'连接与设置',goal:'目标详情'})[view];$('#content').innerHTML=({overview,needs,members,learning,settings,goal:detail}[view]||overview)()}
function field(label,name,value='',type='text'){return `<label for="f-${name}">${label}</label>${type==='textarea'?`<textarea id="f-${name}" name="${name}" required>${esc(value)}</textarea>`:`<input id="f-${name}" name="${name}" type="${type}" value="${esc(value)}" required>`}`}
function dialog(title,html,submit){$('#dialog-title').textContent=title;$('#editor-form').innerHTML=html+`<div class="actions"><button type="button" id="cancel-dialog">取消</button><button class="primary" type="submit">保存并继续</button></div>`;$('#cancel-dialog').onclick=()=>$('#editor').close();$('#editor-form').onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{await submit(Object.fromEntries(new FormData(e.target)));$('#editor').close();toast('已保存');await refresh()}catch(e){toast(e.message)}finally{b.disabled=false}};$('#editor').showModal()}
const dialogueLabels={goal:{title:'目标名称',objective:'方向与结果',acceptance:'成功标准',horizon:'目标周期',boundaries:'执行边界'},member:{name:'姓名',role:'职位 / 角色',description:'能力与可贡献事项',skills:'能力标签',decision_scopes:'可判断范围'}};
function completeDraft(kind,draft){const required=kind==='goal'?['title','objective','acceptance']:['name','role','description'];return required.every(k=>Array.isArray(draft[k])?draft[k].length:String(draft[k]||'').trim())}
function draftValue(value){return Array.isArray(value)?value.join('、'):(value||'尚待补充')}
function missingText(c,labels){return c.missing.map(k=>labels[k]||k).join('、')}
function renderConversation(){const c=conversation,labels=dialogueLabels[c.kind],canCommit=c.ready&&completeDraft(c.kind,c.draft);$('#editor-form').innerHTML=`<div class="chat-flow" aria-live="polite">${c.history.map(m=>`<div class="chat-message ${m.role}"><span>${m.role==='assistant'?'AI':'你'}</span><p class="pre">${esc(m.text)}</p></div>`).join('')}</div>${c.options.length?`<div class="genui"><div class="genui-label">可直接选择，也可以继续自己描述</div><div class="option-grid">${c.options.map((o,i)=>`<button type="button" data-dialogue-option="${i}"><b>${esc(o.label)}</b><small>${esc(o.value)}</small></button>`).join('')}</div></div>`:''}<details class="draft-card" ${c.ready?'open':''}><summary>当前${c.kind==='goal'?'目标':'成员'}草稿 ${c.missing.length?`· 还缺 ${esc(missingText(c,labels))}`:'· 可创建'}</summary>${Object.entries(labels).map(([k,label])=>`<div><span>${label}</span><p class="pre">${esc(draftValue(c.draft[k]))}</p></div>`).join('')}</details><label for="dialogue-input">继续补充</label><textarea id="dialogue-input" name="message" placeholder="可以一次写很多，也可以只回答 AI 当前的问题" required></textarea><p class="hint">Enter 发送，Shift + Enter 换行。选项只是建议，点击后仍会由 AI 整理进草稿。</p><div class="actions"><button type="button" id="cancel-dialog">取消</button>${canCommit?'<button type="button" id="commit-dialogue">确认创建</button>':''}<button class="primary" type="submit">发送给 AI</button></div>`;
  $('#cancel-dialog').onclick=()=>$('#editor').close();
  $('#editor-form').onsubmit=async e=>{e.preventDefault();await sendDialogue(new FormData(e.target).get('message'))};
  $('#dialogue-input').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();$('#editor-form').requestSubmit()}};
  document.querySelectorAll('[data-dialogue-option]').forEach(b=>b.onclick=()=>{const o=c.options[Number(b.dataset.dialogueOption)];sendDialogue(`我选择「${o.label}」：${o.value}`)});
  const commit=$('#commit-dialogue');if(commit)commit.onclick=commitConversation;
  $('#dialogue-input').focus();
}
async function sendDialogue(message){message=String(message||'').trim();if(!message)return;const c=conversation,input=$('#dialogue-input'),buttons=$('#editor-form').querySelectorAll('button');buttons.forEach(b=>b.disabled=true);input.disabled=true;c.history.push({role:'user',text:message});try{const result=await api('/api/dialogue',{kind:c.kind,message,draft:c.draft,history:c.history.slice(0,-1)});c.draft=result.draft;c.missing=result.missing;c.options=result.options;c.ready=result.ready;c.history.push({role:'assistant',text:result.reply});renderConversation()}catch(e){c.history.pop();toast(e.message);buttons.forEach(b=>b.disabled=false);input.disabled=false}}
async function commitConversation(){const c=conversation,b=$('#commit-dialogue');b.disabled=true;try{if(c.kind==='goal'){const r=await api('/api/goals',c.draft);selected=r.id;view='goal'}else{await api('/api/members',{...c.draft,id:c.id||undefined})}$('#editor').close();toast(c.kind==='goal'?'目标已创建，AI 将开始规划':'成员能力已保存');await refresh()}catch(e){toast(e.message);b.disabled=false}}
function conversationalEditor(kind,existing={}){const defaults=kind==='goal'?{title:'',objective:'',acceptance:'',horizon:'三个月',boundaries:'先在本地推进；对外发送、发布、付费和生产操作需要明确授权。'}:{name:'',role:'',description:'',skills:[],decision_scopes:[]};conversation={kind,id:existing.id||'',draft:{...defaults,...existing},missing:kind==='goal'?['目标名称','方向与结果','成功标准']:['姓名','职位 / 角色','能力与可贡献事项'],options:[],ready:false,history:[{role:'assistant',text:kind==='goal'?'先说说你希望长期推动的业务方向。可以一次把背景、期望结果、周期和限制都告诉我，也可以只从一句话开始。':'请介绍这位成员：是谁、负责什么、擅长完成哪些事情。判断权限只有明确说明后才会记录。'}]};$('#dialog-title').textContent=kind==='goal'?'对话创建业务目标':existing.id?'对话更新成员能力':'对话添加团队成员';renderConversation();$('#editor').showModal()}
$('#close-dialog').onclick=()=>$('#editor').close();
document.addEventListener('click',async e=>{const v=e.target.closest('[data-view]'),g=e.target.closest('[data-goal]'),t=e.target.closest('[data-tab]'),a=e.target.closest('[data-action]');if(v){view=v.dataset.view;render();return}if(g){view='goal';selected=g.dataset.goal;tab='work';render();return}if(t){tab=t.dataset.tab;render();return}if(!a)return;const d=a.dataset;try{switch(d.action){case'new-goal':conversationalEditor('goal');break;
case'new-member':case'edit-member':{const m=state.members.find(m=>m.id===d.id)||{};conversationalEditor('member',m);break}
case'goal-toggle':await api('/api/goal/control',{id:d.id,enabled:d.enabled==='true'});await refresh();break;
case'respond':{const r=state.goals.flatMap(g=>g.requests).find(r=>r.id===d.id);dialog('回应：'+r.title,`<p class="pre">${esc(r.expected)}</p><label for="reply-kind">回应方式</label><select id="reply-kind" name="kind"><option value="reply">补充信息 / 汇报结果</option><option value="correction">纠正任务或调用方式</option>${r.kind==='judge'?'<option value="decision">给出明确判断</option>':''}</select>${r.kind==='judge'?'<label for="decision">判断内容（选择“给出明确判断”时生效）</label><select id="decision" name="decision"><option value="approve">同意</option><option value="reject">拒绝</option><option value="revise">调整方向</option></select>':''}`+field('回应 / 原因 / 结果','text','','textarea')+'<p class="hint">AI 会判断是否足以继续，必要时只追问剩余缺口。</p>',p=>api('/api/respond',{...p,id:r.id}));break}
case'feedback':dialog('补充目标反馈',field('新信息、方向调整或纠正','text','','textarea'),p=>api('/api/goal/feedback',{id:d.id,...p}));break;
case'upload':dialog('提交结果文件','<label for="file">选择文件（最大 8 MB）</label><input id="file" type="file" required><p class="hint">文件将放入该目标的工作目录，交给 AI 检查。</p>',async()=>{const file=$('#file').files[0];if(file.size>8000000)throw Error('文件大于 8 MB');const buf=new Uint8Array(await file.arrayBuffer());let raw='';for(let i=0;i<buf.length;i+=8192)raw+=String.fromCharCode(...buf.subarray(i,i+8192));return api('/api/upload',{goal_id:d.goalId,request_id:d.id,name:file.name,data:btoa(raw)})});break;
case'new-monitor':dialog('添加反馈监测',field('监测名称','title')+field('Goal 工作目录内文件路径','path','metrics.json')+field('检查间隔','cadence','1h')+'<label for="due">首次检查（留空立即检查）</label><input id="due" name="next_due_at" type="datetime-local"><label for="expiry">结束时间（可选）</label><input id="expiry" name="expires_at" type="datetime-local"><p class="hint">支持文本或 JSON 指标文件。先建立基线，后续有变化时 AI 评估影响；无变化时安静等待。</p>',p=>api('/api/monitors',{...p,goal_id:d.goalId,next_due_at:p.next_due_at?new Date(p.next_due_at).toISOString():'',expires_at:p.expires_at?new Date(p.expires_at).toISOString():''}));break;
case'monitor-run':case'monitor-toggle':await api('/api/monitor/control',{id:d.id,goal_id:d.goalId,operation:d.action==='monitor-run'?'run':d.operation});await refresh();break;
case'check':a.disabled=true;await api('/api/connections/check',{provider:d.provider});toast('连接检查完成');await refresh();break;
case'settings':dialog('持续运行设置',`<label for="local-member">本机对应成员</label><select id="local-member" name="local_member_id"><option value="">尚未选择</option>${state.members.map(m=>`<option value="${m.id}" ${m.id===state.settings.local_member_id?'selected':''}>${esc(m.name)}</option>`).join('')}</select><label><input name="airjelly_enabled" type="checkbox" ${state.settings.airjelly_enabled?'checked':''}>启用 AirJelly 行为记录同步</label>`+field('24 小时模型调用上限','daily_model_calls',state.settings.daily_model_calls,'number'),p=>api('/api/settings',{...p,airjelly_enabled:p.airjelly_enabled==='on',daily_model_calls:Number(p.daily_model_calls)}));break;
case'infer':await api('/api/capabilities/infer',{member_id:d.id});toast('已安排能力线索提取，完成后将显示在成员卡片');break;
case'toggle-lesson':await api('/api/lesson',{id:d.id,active:d.enabled==='true'});await refresh();break;
case'edit-lesson':{const l=state.lessons.find(l=>l.id===d.id);dialog('编辑适用经验',field('经验内容','text',l.text,'textarea'),p=>api('/api/lesson',{id:l.id,...p}));break}
}}catch(e){toast(e.message)}finally{a.disabled=false}});
document.addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target.matches('[data-goal]'))e.target.click()});
refresh();setInterval(refresh,5000);
