import type { ReviewExportLabels } from "../../data/delivery-review.js";

export const goalAcceptanceContractCopy = {
  en: {
    title: "Goal acceptance contract", boundary: "Read-only owner contract. Task association and artifact checks are separate; neither automatically approves or completes the Goal.",
    scope: "Contract coverage", allWork: "All advancement work (including future tasks)", selectedWork: "Only explicitly selected tasks",
    source: "Goal source", revision: "Contract revision", digest: "Contract digest", objective: "Objective", criteria: "Acceptance criteria", nonGoals: "Outside scope",
    tasks: "Task associations", verification: "Artifact verification", unknown: "Unknown", noTasks: "No task associations reported. Coverage is unknown.",
    noCriteria: "No acceptance criteria reported.", retained: "Retained snapshot; refresh to read current acceptance facts.",
    taskState: { ready: "Task association confirmed", unbound: "Task association missing", stale: "Task association stale" },
    verificationState: { unverified: "Artifact checks not verified", accepted: "Artifact checks passed", failed: "Artifact checks failed", stale: "Artifact checks stale", partial: "Task checks passed; Goal-wide verification unknown", held: "Task associations require confirmation" },
    notApplicable: "Outside the current task gate", heldTasks: "Tasks held", receipt: "Recorded artifact checks", receiptNote: "Recorded results use the revision below. The current contract status above accounts for stale checks and task holds.",
    operation: "Verification reference", verificationScope: "Verification scope", allCriteria: "All contract criteria", passed: "Passed", failed: "Failed", exitCode: "Exit code",
    help: "Setup and readback", guide: "Owner setup guide (v0)", guidance: "The local Goal owner configures this contract through the CLI using configure --document and the inspected --expected-provider-revision. Changes and verification require --execute. Inspect before changing the contract; refresh this snapshot afterward. Disable with the current provider revision to hide this section.",
  },
  "zh-CN": {
    title: "Goal 验收合同", boundary: "只读的所有者合同。任务关联与产物检查是独立事实，均不会自动批准或完成 Goal。",
    scope: "合同覆盖范围", allWork: "全部推进任务（包括后续新增任务）", selectedWork: "仅明确选定的任务",
    source: "Goal 来源", revision: "合同版本", digest: "合同摘要", objective: "目标", criteria: "验收条件", nonGoals: "范围之外",
    tasks: "任务关联", verification: "产物验证", unknown: "未知", noTasks: "未提供任务关联，覆盖范围未知。",
    noCriteria: "未提供验收条件。", retained: "当前保留旧快照，请刷新读取最新验收事实。",
    taskState: { ready: "任务关联已确认", unbound: "任务关联缺失", stale: "任务关联已过期" },
    verificationState: { unverified: "产物检查未验证", accepted: "产物检查通过", failed: "产物检查失败", stale: "产物检查已过期", partial: "任务检查通过；Goal 整体验证未知", held: "任务关联需要确认" },
    notApplicable: "不属于当前任务门禁范围", heldTasks: "受阻任务", receipt: "已记录的产物检查", receiptNote: "记录对应下方版本。上方当前合同状态已考虑检查过期和任务阻塞。",
    operation: "验证引用", verificationScope: "验证范围", allCriteria: "全部合同条件", passed: "通过", failed: "失败", exitCode: "退出码",
    help: "配置与读回", guide: "所有者配置指南（v0）", guidance: "本地 Goal 所有者通过 CLI 的 configure --document 配置合同，并提供 inspect 读到的 --expected-provider-revision。变更和验证都需要 --execute。变更前先检查合同，操作后刷新此快照；使用当前 provider revision 执行 disable 可隐藏本区块。",
  },
};
export type GoalAcceptanceContractCopy = typeof goalAcceptanceContractCopy.en;

const en = {
  contract: goalAcceptanceContractCopy.en,
  title: "Delivery & evidence", scope: "The delivery chain covers current work, a few predecessors and their evidence. The work map covers every task that is not archived.",
  observed: "Snapshot read", chain: "Delivery chain", relations: "Relationships", acceptance: "Acceptance observations",
  acceptanceBoundary: "Completed tasks and recorded evidence do not certify Goal acceptance.",
  noGraph: "No delivery chain is available in this snapshot. This does not mean all work is complete.",
  incomplete: "Some related information is missing or not expanded.",
  unavailable: "Unknown", refs: "Source references", required: "Evidence still required", guards: "Pending decisions", next: "Next action",
  owner: "Owner", reason: "Reason", historical: "Historical observations", checks: "Component checks", missingSources: "Missing sources", observedScope: "Observation coverage",
  kind: { deliverable: "Work", gate: "Decision", gate_summary: "Other decisions", lease: "Ownership", validation: "Validation", repair: "Recovery", handoff: "Handoff", evidence: "Evidence" },
  state: { open: "Open", ready: "Ready", blocked: "Blocked", done: "Done", waiting: "Waiting", unknown: "Unknown" },
  relation: { depends_on: "depends on", blocks: "blocks", validates: "validates / contextualizes", repairs: "repairs", audits: "audits", continues: "continues", hands_off_to: "hands off to", supersedes: "supersedes" },
  refresh: "Refresh snapshot", export: "Export delivery snapshot", exported: "Snapshot downloaded", loading: "Reading the current delivery chain…",
  error: "The delivery snapshot could not be read. Refresh to retry.",
  refreshError: "Refresh failed. The previous snapshot remains visible; refresh before opening linked work or exporting.",
  changed: "Workspace facts changed after this snapshot. Refresh before opening linked work or exporting.",
  search: "Search title, owner or reference", all: "All nodes", conditions: "Conditions & owners", evidence: "Evidence & handoffs", related: "Directly related",
  map: "Map", list: "List", view: "Delivery chain layout", filter: "Delivery chain focus", visible: "Visible", empty: "No nodes match these filters.",
  reset: "Reset filters", select: "Select a node to trace its relationships and open its source.",
  work: "Work", context: "Evidence & recovery", details: "Selected item", noRelations: "No relationships are recorded for this item.",
  openTask: "Open task", openGate: "Review decision", openRun: "Open execution",
  sourceUnavailable: "The linked item is not in the current workspace. Use its reference in the task board or CLI.",
  omittedGates: "Decisions not expanded", missing: "Missing predecessors", clipped: "Expansion limited", sourceClipped: "Source truncated", yes: "Yes", no: "No", chainOnly: "Bounded chain", exportFailed: "Download failed. Please retry.",
  updating: "Workspace facts changed. Updating this snapshot…",
  workMap: {
    title: "Work map", canvas: "Work map canvas", focus: "Map focus", current: "Current work", all: "Everything",
    zoom: "Map zoom", zoomOut: "Zoom out", zoomIn: "Zoom in", fit: "Fit",
    boundary: "Arrows follow recorded task links. The map shows relationships; it does not decide what can run or whether the Goal is accepted.",
    tasksDone: "tasks done", blocked: "blocked", waiting: "waiting", decisions: "need your decision", watches: "watching",
    hidden: "finished or deferred, hidden", unlinked: "Not linked to other work", empty: "This Goal has no tasks yet.",
    owner: "Owner", showMore: "Show {count} more", showFewer: "Show fewer", doneBefore: "+{count} done before", noLinks: "No task links are recorded between these items yet.",
    unavailable: "This source does not provide a work map.",
    kind: { deliverable: "Task", gate: "Decision", monitor: "Watch" },
    tone: { decision: "Needs you", blocked: "Blocked", open: "Open", waiting: "Waiting", done: "Done", unknown: "Unknown" },
    before: "Before this", after: "After this", nothingBefore: "No recorded prerequisites.", nothingAfter: "Nothing recorded depends on this yet.",
    relation: { depends_on: "Required", continues: "Follow-up", supersedes: "Replaces" },
    legend: "Line styles", open: "Open details", noSource: "Details for this item are not loaded in the workspace.",
    select: "Select an item to trace what it needs and what it leads to.", selected: "Selected item",
    incomplete: "Some work is not on this map.", omitted: "Not shown", missingEnds: "Missing linked items", truncated: "Source truncated", cycles: "Circular links",
  },
} satisfies ReviewExportLabels & Record<string, unknown>;

const zh: typeof en = {
  contract: goalAcceptanceContractCopy["zh-CN"],
  title: "交付与依据", scope: "交付链仅含当前工作、少量前序及其证据；工作地图包含全部未归档任务。",
  observed: "快照读取时间", chain: "交付链", relations: "关联关系", acceptance: "验收观察",
  acceptanceBoundary: "任务完成、已有证据均不等于 Goal 已通过验收。",
  noGraph: "当前快照没有可展示的交付链，这不代表工作已经全部完成。",
  incomplete: "部分关联信息缺失或未展开。",
  unavailable: "未知", refs: "来源引用", required: "仍需补齐的证据", guards: "待你处理", next: "下一步",
  owner: "负责人", reason: "原因", historical: "历史观察", checks: "组成检查", missingSources: "缺失来源", observedScope: "观察范围",
  kind: { deliverable: "工作", gate: "决策", gate_summary: "其他决策", lease: "责任归属", validation: "验证", repair: "恢复", handoff: "交接", evidence: "证据" },
  state: { open: "待处理", ready: "就绪", blocked: "受阻", done: "已完成", waiting: "等待", unknown: "未知" },
  relation: { depends_on: "依赖", blocks: "阻塞", validates: "验证 / 提供背景", repairs: "修复", audits: "复核", continues: "延续", hands_off_to: "交接给", supersedes: "替代" },
  refresh: "刷新快照", export: "导出交付快照", exported: "快照已下载", loading: "正在读取当前交付链…",
  error: "交付快照读取失败，请刷新重试。",
  refreshError: "刷新失败，当前保留上次快照；请刷新后再打开关联工作或导出。",
  changed: "工作区状态已在此快照之后变化，请刷新后再打开关联工作或导出。",
  search: "搜索标题、负责人或引用", all: "全部节点", conditions: "条件与责任", evidence: "证据与交接", related: "直接关联",
  map: "关系图", list: "列表", view: "交付链布局", filter: "交付链范围", visible: "当前显示", empty: "没有匹配当前筛选的节点。",
  reset: "重置筛选", select: "选择一个节点，追溯关联关系并打开来源。",
  work: "工作", context: "证据与恢复", details: "选中事项", noRelations: "当前快照未记录此事项的关联关系。",
  openTask: "打开任务", openGate: "查看决策", openRun: "打开执行",
  sourceUnavailable: "关联事项未出现在当前工作区，可使用其引用到任务看板或 CLI 查找。",
  omittedGates: "未展开决策", missing: "缺失前序", clipped: "展开受限", sourceClipped: "来源被裁剪", yes: "是", no: "否", chainOnly: "当前局部链", exportFailed: "下载失败，请重试。",
  updating: "工作区状态已变化，正在更新此快照…",
  workMap: {
    title: "工作地图", canvas: "工作地图画布", focus: "地图范围", current: "当前工作", all: "全部",
    zoom: "地图缩放", zoomOut: "缩小", zoomIn: "放大", fit: "适配",
    boundary: "箭头来自已记录的任务关联。地图只展示关系，不决定哪些工作可以执行，也不代表 Goal 已通过验收。",
    tasksDone: "项任务已完成", blocked: "受阻", waiting: "等待", decisions: "需你决策", watches: "持续监控",
    hidden: "项已完成或延后的工作已隐藏", unlinked: "未与其他工作关联", empty: "此 Goal 还没有任务。",
    owner: "负责人", showMore: "显示其余 {count} 项", showFewer: "收起", doneBefore: "另有 {count} 项已完成前序", noLinks: "这些事项之间还没有记录的任务关联。",
    unavailable: "此来源不提供工作地图。",
    kind: { deliverable: "任务", gate: "决策", monitor: "监控" },
    tone: { decision: "需要你", blocked: "受阻", open: "待处理", waiting: "等待", done: "已完成", unknown: "未知" },
    before: "之前", after: "之后", nothingBefore: "未记录前置工作。", nothingAfter: "暂无记录依赖此项的工作。",
    relation: { depends_on: "必需", continues: "延续", supersedes: "替代" },
    legend: "连线样式", open: "打开详情", noSource: "此事项的详情未加载到工作区。",
    select: "选择一项，查看它依赖什么、又会带来什么。", selected: "选中事项",
    incomplete: "部分工作未出现在此地图中。", omitted: "未显示", missingEnds: "关联事项未找到", truncated: "来源被裁剪", cycles: "循环关联",
  },
};
export const deliveryReviewCopy = { en, "zh-CN": zh };
