# Generated by scripts/generate_semantic_bindings.py; do not edit.
# Value owner: loopx/control_plane/content_digest.ts
# Existing imports remain stable; Python performs no runtime bridge call.
from __future__ import annotations

import re

ENVELOPED_SHA256_PATTERN = re.compile("^sha256:[0-9a-f]{64}$")
BARE_SHA256_PATTERN = re.compile("^[0-9a-f]{64}$")
