#!/usr/bin/env python3
"""Generate the quota/frontier TypeScript bindings and vocabulary glossary.

Run with ``uv run python scripts/generate_semantic_bindings.py [--check]``.
The Python enum remains the value owner during M1. Product code does not import
this generator or the build-time semantic registry.
"""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from loopx.semantics.inventory import load_sources  # noqa: E402
from loopx.semantics.python_production import enum_members  # noqa: E402
from loopx.semantics.production import quota_action_domain  # noqa: E402

REGISTRY = ROOT / 'loopx/semantics/vocabulary_v0.json'
BINDING = ROOT / 'loopx/control_plane/quota/effective_action.generated.ts'
FRONTIER_BINDING = ROOT / 'loopx/control_plane/agents/agent_scope_frontier.generated.ts'
GLOSSARY = ROOT / 'docs/reference/glossary.md'
DIGEST_OWNER = ROOT / 'loopx/control_plane/content_digest.ts'
DIGEST_BINDING = DIGEST_OWNER.with_suffix('.py')


def render_binding(members: dict[str, str], source_owner: str, symbol: str, array: str) -> str:
    lines = [
        '// Generated by scripts/generate_semantic_bindings.py; do not edit.',
        f'// Value owner: {source_owner}',
        '',
        f'export const {array} = [',
        *(f'  {json.dumps(value)},' for value in members.values()),
        '] as const;',
        f'export type {symbol}Value = (typeof {array})[number];',
        '',
        f'export const {symbol} = {{',
        *(f'  {name}: {array}[{index}],' for index, name in enumerate(members)),
        '} as const;',
        '',
    ]
    return '\n'.join(lines)


def render_glossary(registry: dict) -> str:
    lines = [
        '# Semantic Vocabulary Glossary / 语义词表',
        '',
        '<!-- Generated by scripts/generate_semantic_bindings.py; do not edit. -->',
        '',
        'This is a generated view of the curated registry, not another authority.',
        '这是注册表的生成视图；修改定义应编辑 owner 和注册表，然后重新生成。',
        '',
        'Equal spellings or value sets do not prove equal meaning. Producers write',
        'values; consumers interpret or pass them through; only owners define sets.',
        '同名或相同值集不等于同一语义。生产者写值，消费者解释或透传，owner 定义集合。',
        '',
        'See the [RFC](../architecture/rfcs/semantic-vocabulary-convergence-v0.md)',
        'and its [中文版本](../architecture/rfcs/semantic-vocabulary-convergence-v0.zh-CN.md)',
        'for scope, compatibility, proof boundaries and migration gates.',
        '',
    ]
    for name, vocabulary in sorted(registry['vocabularies'].items()):
        lines += [f'## {name}', '', vocabulary['meaning'], '',
                  f"- Tier / 层级: `{vocabulary['tier']}`; status / 状态: `{vocabulary['status']}`."]
        for runtime, owner in vocabulary['owners'].items():
            if owner:
                module, symbol = owner.split('::')
                lines.append(f'- {runtime}: [`{symbol}`](../../{module}).')
        lines.append('- Values / 值: ' + ', '.join(f'`{value}`' for value in vocabulary['values']) + '.')
        if compatibility := vocabulary.get('compatibility_only'):
            lines.append('- Compatibility only / 兼容保留: ' + ', '.join(f'`{value}`' for value in sorted(compatibility)) + '.')
        lines.append('')
    return '\n'.join(lines)


def render_digest_binding(source: str) -> str:
    # These two flagless literal patterns are a deliberately narrow cross-runtime
    # contract. Reject extra syntax rather than execute TS or guess its meaning.
    declarations = re.sub(r"/\*.*?\*/", "", source, flags=re.S).strip().splitlines()
    patterns = {}
    for declaration in declarations:
        if not declaration.strip():
            continue
        match = re.fullmatch(r"export const (ENVELOPED_SHA256_PATTERN|BARE_SHA256_PATTERN) = /([^/]+)/;", declaration.strip())
        if match is None or match[1] in patterns:
            raise ValueError("digest owner requires exactly two flagless literal pattern exports")
        # Only the shared digest alphabet, anchors and quantifier are supported;
        # language-specific regex features require a reviewed generator change.
        if re.fullmatch(r"\^(?:sha256:)?\[0-9a-f\]\{[1-9][0-9]*\}\$", match[2]) is None:
            raise ValueError("digest owner pattern is outside the shared regex subset")
        patterns[match[1]] = match[2]
    if set(patterns) != {"ENVELOPED_SHA256_PATTERN", "BARE_SHA256_PATTERN"}:
        raise ValueError("digest owner requires both exports")
    return "\n".join([
        '# Generated by scripts/generate_semantic_bindings.py; do not edit.',
        '# Value owner: loopx/control_plane/content_digest.ts',
        '# Existing imports remain stable; Python performs no runtime bridge call.',
        'from __future__ import annotations', '', 'import re', '',
        *(f'{name} = re.compile({json.dumps(pattern)})' for name, pattern in patterns.items()), '',
    ])


def verified_generated_paths():
    """Qualify generated bindings by rebuilding, not by a filename or comment."""
    artifacts = build_artifacts()
    for path, content in artifacts.items():
        if not path.is_file() or path.read_text(encoding="utf-8") != content:
            raise ValueError(f"stale generated semantic artifact: {path.relative_to(ROOT)}; run scripts/generate_semantic_bindings.py")
    return frozenset(path.relative_to(ROOT).as_posix() for path in artifacts)


def build_artifacts() -> dict[Path, str]:
    registry = json.loads(REGISTRY.read_text(encoding='utf-8'))
    sources = {source.path: source for source in load_sources(ROOT)}
    artifacts = {}
    for name, path, array in (
        ('effective_action', BINDING, 'EFFECTIVE_ACTIONS'),
        ('agent_scope_frontier_action', FRONTIER_BINDING, 'AGENT_SCOPE_FRONTIER_ACTIONS'),
    ):
        vocabulary = registry['vocabularies'][name]
        owner = vocabulary['owners']['python']
        module, symbol = owner.split('::')
        if module not in sources:
            raise ValueError(f'{name} owner must be a tracked source')
        members = enum_members(sources[module], symbol, strict=True)
        values = list(members.values())
        if (len(values) != len(set(values)) or set(values) != set(vocabulary['values'])):
            raise ValueError(f'{name} owner and registry differ; reconcile them before generation')
        artifacts[path] = render_binding(members, owner, symbol, array)
    quota_action_domain(registry)
    artifacts[BINDING] += (
        '\nimport type { AgentScopeFrontierActionValue } from "../agents/agent_scope_frontier.generated.ts";\n'
        'export type QuotaEffectiveActionValue = EffectiveActionValue | AgentScopeFrontierActionValue;\n'
    )
    artifacts[GLOSSARY] = render_glossary(registry)
    artifacts[DIGEST_BINDING] = render_digest_binding(DIGEST_OWNER.read_text(encoding="utf-8"))
    return artifacts


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='fail without writing if either artifact is stale')
    args = parser.parse_args()
    stale = []
    for path, expected in build_artifacts().items():
        if path.is_file() and path.read_text(encoding='utf-8') == expected:
            continue
        stale.append(path.relative_to(ROOT).as_posix())
        if not args.check:
            path.write_text(expected, encoding='utf-8')
    if stale and args.check:
        print('Stale semantic artifacts: ' + ', '.join(stale) +
              '; run uv run python scripts/generate_semantic_bindings.py', file=sys.stderr)
        return 1
    print('semantic bindings/glossary: ' + ('generated' if stale else 'up to date'))
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
